package com.quizlet.quizletandroid;

import android.app.Activity;
import androidx.appcompat.widget.C0122z;
import com.google.android.gms.internal.mlkit_vision_common.AbstractC3502n4;
import com.quizlet.features.flashcards.InterfaceC4231e;
import com.quizlet.features.infra.navigation.InterfaceC4341a;
import com.quizlet.features.infra.navigation.InterfaceC4342b;
import com.quizlet.features.infra.navigation.InterfaceC4343c;
import com.quizlet.features.infra.navigation.InterfaceC4344d;
import com.quizlet.quizletandroid.ui.common.ads.C4636c;
import com.quizlet.quizletandroid.ui.common.dialogs.TextOverlayDialogFragment;
import com.quizlet.quizletandroid.ui.joincontenttofolder.SelectableFolderListFragment;
import com.quizlet.quizletandroid.ui.learnpaywall.LearnPaywallFragment;
import com.quizlet.quizletandroid.ui.profile.UserFolderListFragment;
import com.quizlet.quizletandroid.ui.profile.UserSetListFragment;
import com.quizlet.quizletandroid.ui.startpage.nav2.HideRecommendationFeedbackFragment;
import com.quizlet.quizletandroid.ui.startpage.nav2.RecommendationsActionOptionsFragment;
import com.quizlet.quizletandroid.ui.startpage.nav2.Y;
import com.quizlet.quizletandroid.ui.studymodes.testmode.fragments.TestStudyModeResultsLoadingFragment;
import com.quizlet.uicommon.ui.common.dialogs.ConfirmationModalFragment;
import com.quizlet.uicommon.ui.common.dialogs.ImageOverlayDialogFragment;
import com.quizlet.uicommon.ui.common.dialogs.info.InfoModalFragment;

/* renamed from: com.quizlet.quizletandroid.e, reason: case insensitive filesystem */
/* loaded from: classes3.dex */
public final class C4622e implements com.quizlet.ads.ui.activity.c, com.quizlet.explanations.questiondetail.ui.b, com.quizlet.explanations.textbook.ui.a, com.quizlet.features.achievements.ui.b, com.quizlet.features.blocks.e, com.quizlet.features.emailconfirmation.ui.activities.k, com.quizlet.features.emailconfirmation.ui.activities.r, InterfaceC4231e, com.quizlet.features.flashcards.di.a, com.quizlet.features.folders.b, com.quizlet.features.folders.composables.r, com.quizlet.features.notes.detail.b, com.quizlet.features.notes.paywall.d, com.quizlet.features.notes.upload.b, com.quizlet.features.onboarding.flashcards.h, com.quizlet.features.onboarding.navigation.f, com.quizlet.features.onboarding.survey.h, com.quizlet.features.paywall.c, com.quizlet.features.practicetest.c, com.quizlet.features.practicetest.di.a, com.quizlet.features.questionnaire.navigation.e, com.quizlet.features.setpage.c, com.quizlet.features.setpage.s, com.quizlet.features.settings.a, com.quizlet.features.settings.di.a, com.quizlet.features.universaluploadflow.b, com.quizlet.features.universaluploadflow.di.a, com.quizlet.features.userprofile.ui.b, com.quizlet.login.b, com.quizlet.login.di.a, com.quizlet.quizletandroid.ui.d, com.quizlet.quizletandroid.ui.classcreation.e, com.quizlet.quizletandroid.ui.deeplinkinterstitial.f, com.quizlet.quizletandroid.ui.diagramming.f, com.quizlet.quizletandroid.ui.globalnav.j, com.quizlet.quizletandroid.ui.globalnav.di.a, com.quizlet.quizletandroid.ui.group.b, com.quizlet.quizletandroid.ui.group.addclassset.b, com.quizlet.quizletandroid.ui.joincontenttofolder.f, com.quizlet.quizletandroid.ui.live.d, com.quizlet.quizletandroid.ui.live.e, com.quizlet.quizletandroid.ui.live.interstitial.b, com.quizlet.quizletandroid.ui.login.j, com.quizlet.quizletandroid.ui.login.p, com.quizlet.quizletandroid.ui.onboarding.ui.c, com.quizlet.quizletandroid.ui.preview.d, com.quizlet.quizletandroid.ui.profile.c, com.quizlet.quizletandroid.ui.qrcodes.c, com.quizlet.quizletandroid.ui.search.a, com.quizlet.quizletandroid.ui.setcreation.activities.e, com.quizlet.quizletandroid.ui.setcreation.activities.i, com.quizlet.quizletandroid.ui.setcreation.activities.j, com.quizlet.quizletandroid.ui.setcreation.activities.k, com.quizlet.quizletandroid.ui.setcreation.activities.l, com.quizlet.quizletandroid.ui.setcreation.activities.m, com.quizlet.quizletandroid.ui.setcreation.activities.q, com.quizlet.quizletandroid.ui.setpage.addset.b, com.quizlet.quizletandroid.ui.sharereceiver.a, com.quizlet.quizletandroid.ui.shortcuts.b, com.quizlet.quizletandroid.ui.studymodes.assistant.n, com.quizlet.quizletandroid.ui.studymodes.assistant.settings.j, com.quizlet.quizletandroid.ui.studymodes.assistant.settings.di.a, com.quizlet.quizletandroid.ui.studymodes.match.activity.c, com.quizlet.quizletandroid.ui.studymodes.match.settings.a, com.quizlet.quizletandroid.ui.studymodes.testmode.activities.g, com.quizlet.quizletandroid.ui.studymodes.write.d, com.quizlet.quizletandroid.ui.studymodes.write.m, com.quizlet.quizletandroid.ui.subject.e, com.quizlet.quizletandroid.ui.usersettings.activities.a, com.quizlet.quizletandroid.ui.usersettings.activities.c, com.quizlet.quizletandroid.ui.webpages.b, com.quizlet.security.challenge.activity.e, com.quizlet.upgrade.ui.activity.e, dagger.hilt.android.internal.lifecycle.a, dagger.hilt.android.internal.lifecycle.g, dagger.hilt.android.internal.managers.g, dagger.hilt.android.internal.managers.k, dagger.hilt.internal.a {
    public final dagger.internal.c A;
    public final dagger.internal.c B;
    public final dagger.internal.c C;
    public final dagger.internal.c D;
    public final dagger.internal.c E;
    public final dagger.internal.c F;
    public final dagger.internal.c G;
    public final dagger.internal.c H;
    public final dagger.internal.c I;
    public final dagger.internal.c J;
    public final dagger.internal.c K;
    public final dagger.internal.c L;
    public final dagger.internal.c M;
    public final dagger.internal.c N;
    public final dagger.internal.c O;
    public final dagger.internal.c P;
    public final dagger.internal.c Q;
    public final dagger.internal.c R;
    public final dagger.internal.c S;
    public final dagger.internal.c T;
    public final C4596d U;
    public final dagger.internal.c V;
    public final dagger.internal.c W;
    public final dagger.internal.c X;
    public final Activity a;
    public final u b;
    public final C4624g c;
    public final C4622e d = this;
    public final C4596d e;
    public final C4596d f;
    public final C4596d g;
    public final C4596d h;
    public final C4596d i;
    public final dagger.internal.c j;
    public final dagger.internal.c k;
    public final dagger.internal.c l;
    public final dagger.internal.c m;
    public final dagger.internal.c n;
    public final dagger.internal.c o;
    public final dagger.internal.c p;
    public final dagger.internal.c q;
    public final dagger.internal.c r;
    public final dagger.internal.c s;
    public final dagger.internal.c t;
    public final dagger.internal.c u;
    public final dagger.internal.c v;
    public final dagger.internal.c w;
    public final dagger.internal.c x;
    public final dagger.internal.c y;
    public final dagger.internal.c z;

    public C4622e(u uVar, C4624g c4624g, Activity activity) {
        this.b = uVar;
        this.c = c4624g;
        this.a = activity;
        this.e = new C4596d(uVar, c4624g, this, 0);
        this.f = new C4596d(uVar, c4624g, this, 1);
        this.g = new C4596d(uVar, c4624g, this, 2);
        this.h = new C4596d(uVar, c4624g, this, 3);
        this.i = new C4596d(uVar, c4624g, this, 4);
        this.j = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 5));
        this.k = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 6));
        this.l = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 7));
        this.m = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 8));
        this.n = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 9));
        this.o = dagger.internal.d.a(new C4596d(uVar, c4624g, this, 11));
        this.p = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 10));
        this.q = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 12));
        this.r = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 13));
        this.s = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 14));
        this.t = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 15));
        this.u = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 16));
        this.v = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 17));
        this.w = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 18));
        this.x = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 19));
        this.y = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 20));
        this.z = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 21));
        this.A = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 22));
        this.B = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 23));
        this.C = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 24));
        this.D = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 25));
        this.E = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 26));
        this.F = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 27));
        this.G = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 28));
        this.H = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 29));
        this.I = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 30));
        this.J = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 31));
        this.K = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 32));
        this.L = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 33));
        this.M = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 34));
        this.N = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 35));
        this.O = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 36));
        this.P = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 37));
        this.Q = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 38));
        this.R = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 39));
        this.S = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 40));
        this.T = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 41));
        this.U = new C4596d(uVar, c4624g, this, 42);
        this.V = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 43));
        this.W = dagger.internal.d.a(new C4596d(uVar, c4624g, this, 44));
        this.X = dagger.internal.a.b(new C4596d(uVar, c4624g, this, 45));
    }

    public final C4636c a() {
        AbstractC3502n4.i(11, "expectedSize");
        C0122z c0122z = new C0122z(11);
        u uVar = this.b;
        c0122z.u(InfoModalFragment.class, uVar.B0);
        c0122z.u(ConfirmationModalFragment.class, uVar.C0);
        c0122z.u(ImageOverlayDialogFragment.class, uVar.D0);
        c0122z.u(TextOverlayDialogFragment.class, uVar.E0);
        c0122z.u(UserFolderListFragment.class, uVar.F0);
        c0122z.u(UserSetListFragment.class, uVar.G0);
        c0122z.u(LearnPaywallFragment.class, this.e);
        c0122z.u(RecommendationsActionOptionsFragment.class, this.f);
        c0122z.u(HideRecommendationFeedbackFragment.class, this.g);
        c0122z.u(SelectableFolderListFragment.class, this.h);
        c0122z.u(TestStudyModeResultsLoadingFragment.class, this.i);
        return new C4636c(c0122z.h());
    }

    public final com.quizlet.quizletandroid.ui.globalnav.navigation.a b() {
        return new com.quizlet.quizletandroid.ui.globalnav.navigation.a((InterfaceC4341a) this.F.get(), (InterfaceC4344d) this.I.get(), (com.quizlet.features.infra.navigation.e) this.J.get(), (com.quizlet.features.infra.navigation.f) this.K.get(), (com.quizlet.quizletandroid.ui.startpage.nav2.navigation.b) this.L.get(), (com.quizlet.features.infra.navigation.g) this.M.get(), (com.quizlet.features.infra.navigation.h) this.r.get(), (com.quizlet.features.infra.navigation.j) this.n.get(), (com.quizlet.features.infra.navigation.l) this.N.get(), (com.quizlet.features.infra.navigation.m) this.y.get(), (com.quizlet.features.infra.navigation.n) this.O.get(), (com.quizlet.features.infra.navigation.p) this.P.get(), (com.quizlet.features.infra.navigation.s) this.Q.get(), (com.quizlet.features.infra.navigation.u) this.R.get(), (com.quizlet.features.infra.navigation.x) this.s.get(), (com.quizlet.features.infra.navigation.y) this.S.get(), (com.quizlet.features.infra.navigation.z) this.q.get(), (com.quizlet.features.infra.navigation.A) this.v.get(), (com.quizlet.features.infra.navigation.B) this.u.get(), (com.quizlet.features.infra.navigation.C) this.l.get(), (com.quizlet.features.infra.navigation.D) this.x.get(), new com.quizlet.features.universaluploadflow.navigation.d(this.a), (com.quizlet.features.infra.navigation.o) this.T.get(), new com.quizlet.quizletandroid.ui.common.adapter.c(), new com.quizlet.shared.usecase.folderstudymaterials.a(8), new com.quizlet.quizletandroid.ui.debug.a(), (com.quizlet.features.infra.navigation.r) this.C.get(), (com.quizlet.features.infra.navigation.i) this.m.get());
    }

    public final dagger.internal.b c() {
        AbstractC3502n4.i(142, "expectedSize");
        C0122z c0122z = new C0122z(142);
        Boolean bool = Boolean.TRUE;
        c0122z.u("com.quizlet.quizletandroid.ui.login.accountrecovery.signupduplicate.e", bool);
        c0122z.u("com.quizlet.features.achievements.home.a", bool);
        c0122z.u("com.quizlet.features.achievements.notification.f", bool);
        c0122z.u("com.quizlet.features.achievements.viewmodel.b", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.activitycenter.viewmodels.a", bool);
        c0122z.u("com.quizlet.features.folders.addtofolder.viewmodel.m", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.setpage.addset.c", bool);
        c0122z.u("com.quizlet.features.infra.folder.menu.viewmodel.a", bool);
        c0122z.u("com.quizlet.ads.viewmodel.a", bool);
        c0122z.u("com.quizlet.features.settings.viewmodels.b", bool);
        c0122z.u("com.quizlet.features.settings.viewmodels.d", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.usersettings.viewmodels.c", bool);
        c0122z.u("com.quizlet.features.folders.changetags.viewmodel.d", bool);
        c0122z.u("com.quizlet.features.settings.viewmodels.g", bool);
        c0122z.u("com.quizlet.explanations.textbook.chaptermenu.viewmodel.b", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.group.classcontent.viewmodel.a", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.classcreation.i", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.group.classuser.viewmodel.a", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.group.addclassset.viewmodel.a", bool);
        c0122z.u("com.quizlet.features.infra.folder.create.coursefolder.viewmodel.e", bool);
        c0122z.u("com.quizlet.features.infra.folder.create.viewmodel.b", bool);
        c0122z.u("com.quizlet.features.settings.viewmodels.i", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.group.addclassset.viewmodel.b", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.startpage.nav2.viewmodels.h", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.deeplinkinterstitial.i", bool);
        c0122z.u("com.quizlet.features.settings.viewmodels.k", bool);
        c0122z.u("com.quizlet.features.match.viewmodel.d", bool);
        c0122z.u("com.quizlet.diagrams.ui.i", bool);
        c0122z.u("com.quizlet.edgy.ui.viewmodel.e", bool);
        c0122z.u("com.quizlet.edgy.ui.viewmodel.w", bool);
        c0122z.u("com.quizlet.edgy.ui.viewmodel.M", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.setcreation.viewmodels.e", bool);
        c0122z.u("com.quizlet.features.folders.edittags.viewmodel.c", bool);
        c0122z.u("com.quizlet.features.emailconfirmation.viewmodel.f", bool);
        c0122z.u("com.quizlet.features.notes.detail.viewmodels.c", bool);
        c0122z.u("com.quizlet.explanations.textbook.exercisedetail.viewmodel.c", bool);
        c0122z.u("com.quizlet.explanations.landingpage.viewmodel.a", bool);
        c0122z.u("com.quizlet.explanations.feedback.viewmodel.a", bool);
        c0122z.u("com.quizlet.explanations.solution.viewmodel.b", bool);
        c0122z.u("com.quizlet.features.questiontypes.fitb.m", bool);
        c0122z.u("com.quizlet.features.flashcards.settings.j", bool);
        c0122z.u("com.quizlet.features.flashcards.S", bool);
        c0122z.u("com.quizlet.features.folders.viewmodel.N", bool);
        c0122z.u("com.quizlet.features.blocks.g", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.globalnav.viewmodel.e", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.startpage.nav2.viewmodels.L", bool);
        c0122z.u("com.quizlet.features.home.viewmodel.c", bool);
        c0122z.u("com.quizlet.login.intro.viewmodel.e", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.studymodes.assistant.checkpoint.viewmodel.d", bool);
        c0122z.u("com.quizlet.learn.viewmodel.c", bool);
        c0122z.u("com.quizlet.learn.viewmodel.i", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.studymodes.assistant.checkpoint.viewmodel.i", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.studymodes.assistant.settings.grading.viewmodel.g", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.studymodes.assistant.settings.viewmodel.i", bool);
        c0122z.u("com.quizlet.learn.viewmodel.G", bool);
        c0122z.u("com.quizlet.library.viewmodels.d", bool);
        c0122z.u("com.quizlet.library.viewmodels.l", bool);
        c0122z.u("com.quizlet.library.viewmodels.s", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.library.c0", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.setpage.addset.f", bool);
        c0122z.u("com.quizlet.login.login.viewmodel.f", bool);
        c0122z.u("com.quizlet.features.emailconfirmation.viewmodel.m", bool);
        c0122z.u("com.quizlet.login.magiclink.viewmodel.g", bool);
        c0122z.u("com.quizlet.login.magiclink.viewmodel.j", bool);
        c0122z.u("com.quizlet.features.notes.detail.viewmodels.v", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.studymodes.match.viewmodel.a", bool);
        c0122z.u("com.quizlet.features.match.viewmodel.f", bool);
        c0122z.u("com.quizlet.features.match.viewmodel.h", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.studymodes.match.viewmodel.g", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.login.accountrecovery.loginduplicate.d", bool);
        c0122z.u("com.quizlet.features.questiontypes.mcq.l", bool);
        c0122z.u("com.quizlet.explanations.myexplanations.viewmodel.b", bool);
        c0122z.u("com.quizlet.explanations.myexplanations.viewmodel.m", bool);
        c0122z.u("com.quizlet.search.viewmodels.p", bool);
        c0122z.u("com.quizlet.features.infra.folder.tag.viewmodel.d", bool);
        c0122z.u("com.quizlet.login.recovery.forgotpassword.viewmodel.e", bool);
        c0122z.u("com.quizlet.login.oldlogin.o", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.login.viewmodels.f", bool);
        c0122z.u("com.quizlet.features.onboarding.ell.B", bool);
        c0122z.u("com.quizlet.features.onboarding.flashcards.n", bool);
        c0122z.u("com.quizlet.features.onboarding.navigation.p", bool);
        c0122z.u("com.quizlet.features.onboarding.survey.q", bool);
        c0122z.u("com.quizlet.login.parentemail.viewmodel.e", bool);
        c0122z.u("com.quizlet.features.notes.upload.viewmodels.e", bool);
        c0122z.u("com.quizlet.features.practicetest.detail.viewmodel.i", bool);
        c0122z.u("com.quizlet.features.practicetest.results.viewmodel.h", bool);
        c0122z.u("com.quizlet.features.practicetest.takingtest.viewmodel.l", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.profile.o", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.profile.data.h", bool);
        c0122z.u("com.quizlet.explanations.questiondetail.viewmodel.f", bool);
        c0122z.u("com.quizlet.features.questiontypes.basequestion.k", bool);
        c0122z.u("com.quizlet.features.questionnaire.navigation.m", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.live.QuizletLiveViewModel", bool);
        c0122z.u("com.quizlet.features.settings.viewmodels.u", bool);
        c0122z.u("com.quizlet.report.viewmodels.c", bool);
        c0122z.u("com.quizlet.login.resetpassword.viewmodel.c", bool);
        c0122z.u("com.quizlet.features.infra.folder.save.viewmodel.c", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.setcreation.viewmodels.h", bool);
        c0122z.u("com.quizlet.features.notes.paywall.l", bool);
        c0122z.u("com.quizlet.search.viewmodels.r", bool);
        c0122z.u("com.quizlet.search.viewmodels.u", bool);
        c0122z.u("com.quizlet.search.viewmodels.x", bool);
        c0122z.u("com.quizlet.search.viewmodels.A", bool);
        c0122z.u("com.quizlet.search.viewmodels.D", bool);
        c0122z.u("com.quizlet.search.viewmodels.G", bool);
        c0122z.u("com.quizlet.security.challenge.viewmodel.d", bool);
        c0122z.u("com.quizlet.features.infra.folder.create.coursefolder.schoolcourse.viewmodel.o", bool);
        c0122z.u("com.quizlet.features.setpage.viewmodel.selectedtermsmode.b", bool);
        c0122z.u("com.quizlet.features.questiontypes.selfassessment.h", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.onboarding.h", bool);
        c0122z.u("com.quizlet.features.setpage.header.viewmodel.f", bool);
        c0122z.u("com.quizlet.features.setpage.viewmodel.SetPageMobileWebViewModel", bool);
        c0122z.u("com.quizlet.features.setpage.progress.presentation.viewmodel.a", bool);
        c0122z.u("com.quizlet.features.setpage.viewmodel.P", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.preview.viewmodel.g", bool);
        c0122z.u("com.quizlet.features.settings.viewmodels.I", bool);
        c0122z.u("com.quizlet.login.signup.viewmodel.g", bool);
        c0122z.u("com.quizlet.login.signupwall.viewmodel.a", bool);
        c0122z.u("com.quizlet.features.match.viewmodel.i", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.group.addclassset.viewmodel.c", bool);
        c0122z.u("com.quizlet.features.setpage.studypreview.g", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.subject.viewmodel.m", bool);
        c0122z.u("com.quizlet.explanations.textbook.tableofcontents.viewmodel.b", bool);
        c0122z.u("com.quizlet.features.setpage.termlist.viewmodel.j", bool);
        c0122z.u("com.quizlet.features.setpage.terms.viewmodel.c", bool);
        c0122z.u("com.quizlet.search.viewmodels.M", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.studymodes.testmode.start.A", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.studymodes.testmode.viewmodels.t", bool);
        c0122z.u("com.quizlet.quizletandroid.ui.studymodes.testmode.viewmodels.G", bool);
        c0122z.u("com.quizlet.explanations.textbook.viewmodel.c", bool);
        c0122z.u("com.quizlet.features.questiontypes.truefalse.l", bool);
        c0122z.u("com.quizlet.features.universaluploadflow.flashcards.viewmodel.e", bool);
        c0122z.u("com.quizlet.features.universaluploadflow.pastetext.viewmodel.d", bool);
        c0122z.u("com.quizlet.features.universaluploadflow.viewmodel.g", bool);
        c0122z.u("com.quizlet.upgrade.ui.confirmation.c", bool);
        c0122z.u("com.quizlet.upgrade.viewmodel.h", bool);
        c0122z.u("com.quizlet.upgrade.viewmodel.k", bool);
        c0122z.u("com.quizlet.upgrade.viewmodel.n", bool);
        c0122z.u("com.quizlet.features.notes.upload.viewmodels.k", bool);
        c0122z.u("com.quizlet.upgrade.upsell.viewmodel.c", bool);
        c0122z.u("com.quizlet.features.userprofile.data.x", bool);
        c0122z.u("com.quizlet.features.questiontypes.written.o", bool);
        return new dagger.internal.b(c0122z.h());
    }

    public final com.quizlet.features.userprofile.navigation.b d() {
        return new com.quizlet.features.userprofile.navigation.b((InterfaceC4343c) this.D.get(), (com.quizlet.features.infra.navigation.v) this.E.get(), (InterfaceC4341a) this.F.get(), (com.quizlet.features.infra.navigation.A) this.v.get(), (InterfaceC4342b) this.G.get());
    }

    public final com.onetrust.otpublishers.headless.UI.viewmodel.c e() {
        t tVar = this.b.e1;
        C4623f c4623f = this.c.g;
        C4596d c4596d = this.U;
        AbstractC3502n4.h(com.quizlet.quizletandroid.ui.joincontenttofolder.k.class, tVar);
        AbstractC3502n4.h(Y.class, c4623f);
        AbstractC3502n4.h(com.quizlet.quizletandroid.ui.learnpaywall.k.class, c4596d);
        return new com.onetrust.otpublishers.headless.UI.viewmodel.c(com.google.common.collect.C.d(3, new Object[]{com.quizlet.quizletandroid.ui.joincontenttofolder.k.class, tVar, Y.class, c4623f, com.quizlet.quizletandroid.ui.learnpaywall.k.class, c4596d}, null));
    }
}
