package com.google.android.gms.internal.measurement;

/* loaded from: classes2.dex */
public final class Q2 implements P2 {
    public static final F1 A;
    public static final F1 B;
    public static final F1 C;
    public static final F1 D;
    public static final F1 E;
    public static final F1 F;
    public static final F1 G;
    public static final F1 H;
    public static final F1 I;
    public static final F1 J;
    public static final F1 K;
    public static final F1 L;
    public static final F1 M;
    public static final F1 N;
    public static final F1 O;
    public static final F1 P;
    public static final F1 Q;
    public static final F1 R;
    public static final F1 S;
    public static final F1 T;
    public static final F1 U;
    public static final F1 V;
    public static final F1 W;
    public static final F1 X;
    public static final F1 Y;
    public static final F1 Z;
    public static final F1 a;
    public static final F1 a0;
    public static final F1 b;
    public static final F1 b0;
    public static final F1 c;
    public static final F1 c0;
    public static final F1 d;
    public static final F1 d0;
    public static final F1 e;
    public static final F1 e0;
    public static final F1 f;
    public static final F1 f0;
    public static final F1 g;
    public static final F1 g0;
    public static final F1 h;
    public static final F1 h0;
    public static final F1 i;
    public static final F1 i0;
    public static final F1 j;
    public static final F1 j0;
    public static final F1 k;
    public static final F1 k0;
    public static final F1 l;
    public static final F1 l0;
    public static final F1 m;
    public static final F1 m0;
    public static final F1 n;
    public static final F1 n0;
    public static final F1 o;
    public static final F1 o0;
    public static final F1 p;
    public static final F1 p0;
    public static final F1 q;
    public static final F1 q0;
    public static final F1 r;
    public static final F1 r0;
    public static final F1 s;
    public static final F1 s0;
    public static final F1 t;
    public static final F1 t0;
    public static final F1 u;
    public static final F1 v;
    public static final F1 w;
    public static final F1 x;
    public static final F1 y;
    public static final F1 z;

    static {
        androidx.appcompat.app.K k2 = new androidx.appcompat.app.K(B1.a(), true, true);
        a = k2.O(10000L, "measurement.ad_id_cache_time");
        b = k2.O(3600000L, "measurement.app_uninstalled_additional_ad_id_cache_time");
        c = k2.Q("measurement.config.bundle_for_all_apps_on_backgrounded", true);
        d = k2.O(100L, "measurement.max_bundles_per_iteration");
        e = k2.O(86400000L, "measurement.config.cache_time");
        k2.P("measurement.log_tag", "FA");
        f = k2.P("measurement.config.url_authority", "app-measurement.com");
        g = k2.P("measurement.config.url_scheme", "https");
        h = k2.O(1000L, "measurement.upload.debug_upload_interval");
        i = k2.O(3600000L, "measurement.session.engagement_interval");
        j = k2.P("measurement.rb.attribution.event_params", "value|currency");
        k = k2.O(605000L, "measurement.upload.google_signal_max_queue_time");
        l = k2.P("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d");
        m = k2.O(4L, "measurement.lifetimevalue.max_currency_tracked");
        n = k2.O(1L, "measurement.dma_consent.max_daily_dcu_realtime_events");
        o = k2.O(500L, "measurement.upload.max_event_parameter_value_length");
        p = k2.O(100000L, "measurement.store.max_stored_events_per_app");
        q = k2.O(50L, "measurement.experiment.max_ids");
        r = k2.O(200L, "measurement.audience.filter_result_max_count");
        s = k2.O(27L, "measurement.upload.max_item_scoped_custom_parameters");
        t = k2.O(1000L, "measurement.rb.max_trigger_registrations_per_day");
        u = k2.O(0L, "measurement.rb.attribution.max_trigger_uris_queried_at_once");
        v = k2.O(7L, "measurement.rb.attribution.client.min_ad_services_version");
        w = k2.O(60000L, "measurement.alarm_manager.minimum_interval");
        x = k2.O(500L, "measurement.upload.minimum_delay");
        y = k2.O(86400000L, "measurement.monitoring.sample_period_millis");
        z = k2.O(3000L, "measurement.rb.attribution.notify_app_delay_millis");
        A = k2.Q("measurement.config.notify_trigger_uris_on_backgrounded", true);
        B = k2.P("measurement.rb.attribution.app_allowlist", "*");
        C = k2.O(10000L, "measurement.upload.realtime_upload_interval");
        D = k2.O(604800000L, "measurement.upload.refresh_blacklisted_config_interval");
        k2.O(3600000L, "measurement.config.cache_time.service");
        E = k2.O(5000L, "measurement.service_client.idle_disconnect_millis");
        k2.P("measurement.log_tag.service", "FA-SVC");
        F = k2.O(1000L, "measurement.service_client.reconnect_millis");
        k2.P("measurement.sgtm.app_allowlist", "*");
        G = k2.O(1800000L, "measurement.sgtm.batch.retry_interval");
        H = k2.O(10L, "measurement.sgtm.batch.retry_max_count");
        I = k2.O(21600000L, "measurement.sgtm.batch.retry_max_wait");
        J = k2.P("measurement.sgtm.service_upload_apps_list", "");
        K = k2.P("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504");
        L = k2.O(5L, "measurement.sgtm.upload.batches_retrieval_limit");
        M = k2.O(5000L, "measurement.sgtm.upload.max_queued_batches");
        N = k2.O(600000L, "measurement.sgtm.upload.min_delay_after_background");
        O = k2.O(1000L, "measurement.sgtm.upload.min_delay_after_broadcast");
        P = k2.O(5000L, "measurement.sgtm.upload.min_delay_after_startup");
        Q = k2.O(600000L, "measurement.sgtm.upload.retry_interval");
        R = k2.O(21600000L, "measurement.sgtm.upload.retry_max_wait");
        S = k2.O(86400000L, "measurement.upload.stale_data_deletion_interval");
        T = k2.O(16L, "measurement.rb.attribution.max_retry_delay_seconds");
        U = k2.O(90L, "measurement.rb.attribution.client.min_time_after_boot_seconds");
        V = k2.P("measurement.rb.attribution.uri_authority", "google-analytics.com");
        W = k2.O(864000000L, "measurement.rb.attribution.max_queue_time");
        X = k2.P("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion");
        Y = k2.P("measurement.rb.attribution.query_parameters_to_remove", "");
        Z = k2.P("measurement.rb.attribution.uri_scheme", "https");
        a0 = k2.O(604800000L, "measurement.sdk.attribution.cache.ttl");
        b0 = k2.O(7200000L, "measurement.redaction.app_instance_id.ttl");
        c0 = k2.O(43200000L, "measurement.upload.backoff_period");
        d0 = k2.O(15000L, "measurement.upload.initial_upload_delay_time");
        e0 = k2.O(3600000L, "measurement.upload.interval");
        f0 = k2.O(65536L, "measurement.upload.max_bundle_size");
        g0 = k2.O(100L, "measurement.upload.max_bundles");
        h0 = k2.O(500L, "measurement.upload.max_conversions_per_day");
        i0 = k2.O(1000L, "measurement.upload.max_error_events_per_day");
        j0 = k2.O(1000L, "measurement.upload.max_events_per_bundle");
        k0 = k2.O(100000L, "measurement.upload.max_events_per_day");
        l0 = k2.O(50000L, "measurement.upload.max_public_events_per_day");
        m0 = k2.O(518400000L, "measurement.upload.max_queue_time");
        n0 = k2.O(10L, "measurement.upload.max_realtime_events_per_day");
        o0 = k2.O(65536L, "measurement.upload.max_batch_size");
        p0 = k2.O(6L, "measurement.upload.retry_count");
        q0 = k2.O(1800000L, "measurement.upload.retry_time");
        r0 = k2.P("measurement.upload.url", "https://app-measurement.com/a");
        s0 = k2.O(3600000L, "measurement.upload.window_interval");
        t0 = k2.P("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot");
    }
}
