package com.google.android.gms.internal.ads;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import com.google.android.gms.ads.internal.client.zzee;
import com.google.android.gms.ads.internal.client.zzm;
import com.google.android.gms.ads.internal.util.client.VersionInfoParcel;
import com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable;
import com.google.android.gms.internal.mlkit_vision_common.AbstractC3489l3;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/* loaded from: classes2.dex */
public final class zzbur extends AbstractSafeParcelable {
    public static final Parcelable.Creator<zzbur> CREATOR = new C2128h6(10);
    public final long A;
    public final String B;
    public final float C;
    public final int D;
    public final int E;
    public final boolean F;
    public final String G;
    public final boolean H;
    public final String I;
    public final boolean J;
    public final int K;
    public final Bundle L;
    public final String M;
    public final zzee V;
    public final boolean W;
    public final Bundle X;
    public final String Y;
    public final String Z;
    public final int a;
    public final Bundle b;
    public final zzm c;
    public final String c1;
    public final com.google.android.gms.ads.internal.client.zzr d;
    public final boolean d1;
    public final String e;
    public final ArrayList e1;
    public final ApplicationInfo f;
    public final String f1;
    public final PackageInfo g;
    public final ArrayList g1;
    public final String h;
    public final int h1;
    public final String i;
    public final boolean i1;
    public final String j;
    public final boolean j1;
    public final VersionInfoParcel k;
    public final boolean k1;
    public final Bundle l;
    public final ArrayList l1;
    public final int m;
    public final String m1;
    public final ArrayList n;
    public final zzbmg n1;
    public final Bundle o;
    public final String o1;
    public final boolean p;
    public final Bundle p1;
    public final int q;
    public final int r;
    public final float s;
    public final String t;
    public final long u;
    public final String v;
    public final List w;
    public final String x;
    public final zzbfv y;
    public final List z;

    public zzbur(int i, Bundle bundle, zzm zzmVar, com.google.android.gms.ads.internal.client.zzr zzrVar, String str, ApplicationInfo applicationInfo, PackageInfo packageInfo, String str2, String str3, String str4, VersionInfoParcel versionInfoParcel, Bundle bundle2, int i2, ArrayList arrayList, Bundle bundle3, boolean z, int i3, int i4, float f, String str5, long j, String str6, ArrayList arrayList2, String str7, zzbfv zzbfvVar, ArrayList arrayList3, long j2, String str8, float f2, boolean z2, int i5, int i6, boolean z3, String str9, String str10, boolean z4, int i7, Bundle bundle4, String str11, zzee zzeeVar, boolean z5, Bundle bundle5, String str12, String str13, String str14, boolean z6, ArrayList arrayList4, String str15, ArrayList arrayList5, int i8, boolean z7, boolean z8, boolean z9, ArrayList arrayList6, String str16, zzbmg zzbmgVar, String str17, Bundle bundle6) {
        this.a = i;
        this.b = bundle;
        this.c = zzmVar;
        this.d = zzrVar;
        this.e = str;
        this.f = applicationInfo;
        this.g = packageInfo;
        this.h = str2;
        this.i = str3;
        this.j = str4;
        this.k = versionInfoParcel;
        this.l = bundle2;
        this.m = i2;
        this.n = arrayList;
        this.z = arrayList3 == null ? Collections.EMPTY_LIST : Collections.unmodifiableList(arrayList3);
        this.o = bundle3;
        this.p = z;
        this.q = i3;
        this.r = i4;
        this.s = f;
        this.t = str5;
        this.u = j;
        this.v = str6;
        this.w = arrayList2 == null ? Collections.EMPTY_LIST : Collections.unmodifiableList(arrayList2);
        this.x = str7;
        this.y = zzbfvVar;
        this.A = j2;
        this.B = str8;
        this.C = f2;
        this.H = z2;
        this.D = i5;
        this.E = i6;
        this.F = z3;
        this.G = str9;
        this.I = str10;
        this.J = z4;
        this.K = i7;
        this.L = bundle4;
        this.M = str11;
        this.V = zzeeVar;
        this.W = z5;
        this.X = bundle5;
        this.Y = str12;
        this.Z = str13;
        this.c1 = str14;
        this.d1 = z6;
        this.e1 = arrayList4;
        this.f1 = str15;
        this.g1 = arrayList5;
        this.h1 = i8;
        this.i1 = z7;
        this.j1 = z8;
        this.k1 = z9;
        this.l1 = arrayList6;
        this.m1 = str16;
        this.n1 = zzbmgVar;
        this.o1 = str17;
        this.p1 = bundle6;
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        int iN = AbstractC3489l3.n(20293, parcel);
        AbstractC3489l3.m(parcel, 1, 4);
        parcel.writeInt(this.a);
        AbstractC3489l3.c(parcel, 2, this.b);
        AbstractC3489l3.g(parcel, 3, this.c, i);
        AbstractC3489l3.g(parcel, 4, this.d, i);
        AbstractC3489l3.h(parcel, 5, this.e);
        AbstractC3489l3.g(parcel, 6, this.f, i);
        AbstractC3489l3.g(parcel, 7, this.g, i);
        AbstractC3489l3.h(parcel, 8, this.h);
        AbstractC3489l3.h(parcel, 9, this.i);
        AbstractC3489l3.h(parcel, 10, this.j);
        AbstractC3489l3.g(parcel, 11, this.k, i);
        AbstractC3489l3.c(parcel, 12, this.l);
        AbstractC3489l3.m(parcel, 13, 4);
        parcel.writeInt(this.m);
        AbstractC3489l3.j(parcel, 14, this.n);
        AbstractC3489l3.c(parcel, 15, this.o);
        AbstractC3489l3.m(parcel, 16, 4);
        parcel.writeInt(this.p ? 1 : 0);
        AbstractC3489l3.m(parcel, 18, 4);
        parcel.writeInt(this.q);
        AbstractC3489l3.m(parcel, 19, 4);
        parcel.writeInt(this.r);
        AbstractC3489l3.m(parcel, 20, 4);
        parcel.writeFloat(this.s);
        AbstractC3489l3.h(parcel, 21, this.t);
        AbstractC3489l3.m(parcel, 25, 8);
        parcel.writeLong(this.u);
        AbstractC3489l3.h(parcel, 26, this.v);
        AbstractC3489l3.j(parcel, 27, this.w);
        AbstractC3489l3.h(parcel, 28, this.x);
        AbstractC3489l3.g(parcel, 29, this.y, i);
        AbstractC3489l3.j(parcel, 30, this.z);
        AbstractC3489l3.m(parcel, 31, 8);
        parcel.writeLong(this.A);
        AbstractC3489l3.h(parcel, 33, this.B);
        AbstractC3489l3.m(parcel, 34, 4);
        parcel.writeFloat(this.C);
        AbstractC3489l3.m(parcel, 35, 4);
        parcel.writeInt(this.D);
        AbstractC3489l3.m(parcel, 36, 4);
        parcel.writeInt(this.E);
        AbstractC3489l3.m(parcel, 37, 4);
        parcel.writeInt(this.F ? 1 : 0);
        AbstractC3489l3.h(parcel, 39, this.G);
        AbstractC3489l3.m(parcel, 40, 4);
        parcel.writeInt(this.H ? 1 : 0);
        AbstractC3489l3.h(parcel, 41, this.I);
        AbstractC3489l3.m(parcel, 42, 4);
        parcel.writeInt(this.J ? 1 : 0);
        AbstractC3489l3.m(parcel, 43, 4);
        parcel.writeInt(this.K);
        AbstractC3489l3.c(parcel, 44, this.L);
        AbstractC3489l3.h(parcel, 45, this.M);
        AbstractC3489l3.g(parcel, 46, this.V, i);
        AbstractC3489l3.m(parcel, 47, 4);
        parcel.writeInt(this.W ? 1 : 0);
        AbstractC3489l3.c(parcel, 48, this.X);
        AbstractC3489l3.h(parcel, 49, this.Y);
        AbstractC3489l3.h(parcel, 50, this.Z);
        AbstractC3489l3.h(parcel, 51, this.c1);
        AbstractC3489l3.m(parcel, 52, 4);
        parcel.writeInt(this.d1 ? 1 : 0);
        AbstractC3489l3.f(parcel, 53, this.e1);
        AbstractC3489l3.h(parcel, 54, this.f1);
        AbstractC3489l3.j(parcel, 55, this.g1);
        AbstractC3489l3.m(parcel, 56, 4);
        parcel.writeInt(this.h1);
        AbstractC3489l3.m(parcel, 57, 4);
        parcel.writeInt(this.i1 ? 1 : 0);
        AbstractC3489l3.m(parcel, 58, 4);
        parcel.writeInt(this.j1 ? 1 : 0);
        AbstractC3489l3.m(parcel, 59, 4);
        parcel.writeInt(this.k1 ? 1 : 0);
        AbstractC3489l3.j(parcel, 60, this.l1);
        AbstractC3489l3.h(parcel, 61, this.m1);
        AbstractC3489l3.g(parcel, 63, this.n1, i);
        AbstractC3489l3.h(parcel, 64, this.o1);
        AbstractC3489l3.c(parcel, 65, this.p1);
        AbstractC3489l3.o(iN, parcel);
    }
}
