package androidx.compose.material3;

import androidx.compose.ui.graphics.C0861v;

/* loaded from: classes.dex */
public final class Z {
    public final long A;
    public final long B;
    public final long C;
    public final long D;
    public final long E;
    public final long F;
    public final long G;
    public final long H;
    public final long I;
    public final long J;
    public K K;
    public K L;
    public K M;
    public V N;
    public V4 O;
    public V4 P;
    public C0699p0 Q;
    public C0768z1 R;
    public T1 S;
    public D2 T;
    public C0672k3 U;
    public A4 V;
    public A4 W;
    public final long a;
    public final long b;
    public final long c;
    public final long d;
    public final long e;
    public final long f;
    public final long g;
    public final long h;
    public final long i;
    public final long j;
    public final long k;
    public final long l;
    public final long m;
    public final long n;
    public final long o;
    public final long p;
    public final long q;
    public final long r;
    public final long s;
    public final long t;
    public final long u;
    public final long v;
    public final long w;
    public final long x;
    public final long y;
    public final long z;

    public Z(long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j30, long j31, long j32, long j33, long j34, long j35, long j36) {
        this.a = j;
        this.b = j2;
        this.c = j3;
        this.d = j4;
        this.e = j5;
        this.f = j6;
        this.g = j7;
        this.h = j8;
        this.i = j9;
        this.j = j10;
        this.k = j11;
        this.l = j12;
        this.m = j13;
        this.n = j14;
        this.o = j15;
        this.p = j16;
        this.q = j17;
        this.r = j18;
        this.s = j19;
        this.t = j20;
        this.u = j21;
        this.v = j22;
        this.w = j23;
        this.x = j24;
        this.y = j25;
        this.z = j26;
        this.A = j27;
        this.B = j28;
        this.C = j29;
        this.D = j30;
        this.E = j31;
        this.F = j32;
        this.G = j33;
        this.H = j34;
        this.I = j35;
        this.J = j36;
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("ColorScheme(primary=");
        androidx.compose.animation.d0.x(this.a, "onPrimary=", sb);
        androidx.compose.animation.d0.x(this.b, "primaryContainer=", sb);
        androidx.compose.animation.d0.x(this.c, "onPrimaryContainer=", sb);
        androidx.compose.animation.d0.x(this.d, "inversePrimary=", sb);
        androidx.compose.animation.d0.x(this.e, "secondary=", sb);
        androidx.compose.animation.d0.x(this.f, "onSecondary=", sb);
        androidx.compose.animation.d0.x(this.g, "secondaryContainer=", sb);
        androidx.compose.animation.d0.x(this.h, "onSecondaryContainer=", sb);
        androidx.compose.animation.d0.x(this.i, "tertiary=", sb);
        androidx.compose.animation.d0.x(this.j, "onTertiary=", sb);
        androidx.compose.animation.d0.x(this.k, "tertiaryContainer=", sb);
        androidx.compose.animation.d0.x(this.l, "onTertiaryContainer=", sb);
        androidx.compose.animation.d0.x(this.m, "background=", sb);
        androidx.compose.animation.d0.x(this.n, "onBackground=", sb);
        androidx.compose.animation.d0.x(this.o, "surface=", sb);
        androidx.compose.animation.d0.x(this.p, "onSurface=", sb);
        androidx.compose.animation.d0.x(this.q, "surfaceVariant=", sb);
        androidx.compose.animation.d0.x(this.r, "onSurfaceVariant=", sb);
        androidx.compose.animation.d0.x(this.s, "surfaceTint=", sb);
        androidx.compose.animation.d0.x(this.t, "inverseSurface=", sb);
        androidx.compose.animation.d0.x(this.u, "inverseOnSurface=", sb);
        androidx.compose.animation.d0.x(this.v, "error=", sb);
        androidx.compose.animation.d0.x(this.w, "onError=", sb);
        androidx.compose.animation.d0.x(this.x, "errorContainer=", sb);
        androidx.compose.animation.d0.x(this.y, "onErrorContainer=", sb);
        androidx.compose.animation.d0.x(this.z, "outline=", sb);
        androidx.compose.animation.d0.x(this.A, "outlineVariant=", sb);
        androidx.compose.animation.d0.x(this.B, "scrim=", sb);
        androidx.compose.animation.d0.x(this.C, "surfaceBright=", sb);
        androidx.compose.animation.d0.x(this.D, "surfaceDim=", sb);
        androidx.compose.animation.d0.x(this.E, "surfaceContainer=", sb);
        androidx.compose.animation.d0.x(this.F, "surfaceContainerHigh=", sb);
        androidx.compose.animation.d0.x(this.G, "surfaceContainerHighest=", sb);
        androidx.compose.animation.d0.x(this.H, "surfaceContainerLow=", sb);
        androidx.compose.animation.d0.x(this.I, "surfaceContainerLowest=", sb);
        sb.append((Object) C0861v.i(this.J));
        sb.append(')');
        return sb.toString();
    }
}
