package com.quizlet.sharedconfig.study_setting_metadata;

import com.quizlet.generated.enums.E1;
import kotlin.Pair;
import kotlin.collections.V;

/* loaded from: classes3.dex */
public abstract class c {
    public static final Object a = V.f(new Pair(E1.TERM_SIDE, 2L), new Pair(E1.TEST_QUESTION_TYPES, 15L), new Pair(E1.TEST_QUESTION_COUNT, 20L), new Pair(E1.SHUFFLE, 0L), new Pair(E1.INSTANT_FEEDBACK, 0L), new Pair(E1.TAP_TO_PLAY_AUDIO, 0L), new Pair(E1.TEST_SELECTED_ONLY_QUESTION_COUNT, 0L), new Pair(E1.ASSISTANT_MODE_QUESTION_TYPES, 85L), new Pair(E1.ASSISTANT_MODE_WORD_SIDE, 1L), new Pair(E1.ASSISTANT_MODE_DEFINITION_SIDE, 1L), new Pair(E1.ASSISTANT_MODE_WRITTEN_WORD_SIDE, 1L), new Pair(E1.ASSISTANT_MODE_WRITTEN_DEFINITION_SIDE, 1L), new Pair(E1.PROMPT_TERM_SIDES, 22L), new Pair(E1.ANSWER_TERM_SIDES, 22L), new Pair(E1.MATCH_MODE_SIDES, 22L), new Pair(E1.TEST_PROMPT_TERM_SIDES, 22L), new Pair(E1.TEST_ANSWER_TERM_SIDES, 22L), new Pair(E1.TEST_SHOW_IMAGES, 1L), new Pair(E1.LIVE_PLAY_MUSIC, 1L), new Pair(E1.FLEXIBLE_GRADING_ACCEPT_PARTIAL_ANSWERS, 0L), new Pair(E1.FLEXIBLE_GRADING_ACCEPT_ANSWERS_WITH_TYPOS, 1L), new Pair(E1.SMART_GRADING, 1L), new Pair(E1.STUDY_PATH, 0L), new Pair(E1.STUDY_PATH_GOAL, 2L), new Pair(E1.STUDY_PATH_KNOWLEDGE_LEVEL, 0L), new Pair(E1.TASKS_ENABLED, 0L), new Pair(E1.CHECKPOINT_PLAY_MUSIC, 1L), new Pair(E1.GUIDANCE_DISABLED, 1L), new Pair(E1.CARDS_SORTING_ON, 1L), new Pair(E1.CARDS_ANSWER_SIDES, 0L), new Pair(E1.CARDS_PROMPT_SIDES, 0L), new Pair(E1.CARDS_SHUFFLE_RANDOM_SEED, 0L), new Pair(E1.ASSISTANT_COPY_CORRECT_ANSWER_ENABLED, 0L));
}
