package com.google.android.gms.internal.mlkit_vision_camera;

import com.google.android.gms.ads.nonagon.signalgeneration.AbstractC1642h;
import java.util.HashMap;

/* renamed from: com.google.android.gms.internal.mlkit_vision_camera.r0, reason: case insensitive filesystem */
/* loaded from: classes2.dex */
public final class C3384r0 implements com.google.firebase.encoders.c {
    public static final com.google.firebase.encoders.b A;
    public static final com.google.firebase.encoders.b B;
    public static final com.google.firebase.encoders.b C;
    public static final com.google.firebase.encoders.b D;
    public static final com.google.firebase.encoders.b E;
    public static final com.google.firebase.encoders.b F;
    public static final com.google.firebase.encoders.b G;
    public static final com.google.firebase.encoders.b H;
    public static final com.google.firebase.encoders.b I;
    public static final com.google.firebase.encoders.b J;
    public static final com.google.firebase.encoders.b K;
    public static final com.google.firebase.encoders.b L;
    public static final com.google.firebase.encoders.b M;
    public static final com.google.firebase.encoders.b N;
    public static final com.google.firebase.encoders.b O;
    public static final com.google.firebase.encoders.b P;
    public static final com.google.firebase.encoders.b Q;
    public static final com.google.firebase.encoders.b R;
    public static final com.google.firebase.encoders.b S;
    public static final com.google.firebase.encoders.b T;
    public static final com.google.firebase.encoders.b U;
    public static final com.google.firebase.encoders.b V;
    public static final com.google.firebase.encoders.b W;
    public static final com.google.firebase.encoders.b X;
    public static final com.google.firebase.encoders.b Y;
    public static final com.google.firebase.encoders.b Z;
    public static final com.google.firebase.encoders.b a0;
    public static final com.google.firebase.encoders.b b0;
    public static final com.google.firebase.encoders.b c0;
    public static final com.google.firebase.encoders.b d0;
    public static final com.google.firebase.encoders.b e0;
    public static final com.google.firebase.encoders.b f0;
    public static final com.google.firebase.encoders.b g0;
    public static final com.google.firebase.encoders.b h0;
    public static final com.google.firebase.encoders.b i0;
    public static final com.google.firebase.encoders.b j0;
    public static final com.google.firebase.encoders.b k0;
    public static final com.google.firebase.encoders.b l0;
    public static final com.google.firebase.encoders.b m0;
    public static final com.google.firebase.encoders.b n0;
    public static final com.google.firebase.encoders.b o0;
    public static final com.google.firebase.encoders.b q;
    public static final com.google.firebase.encoders.b r;
    public static final com.google.firebase.encoders.b s;
    public static final com.google.firebase.encoders.b t;
    public static final com.google.firebase.encoders.b u;
    public static final com.google.firebase.encoders.b v;
    public static final com.google.firebase.encoders.b w;
    public static final com.google.firebase.encoders.b x;
    public static final com.google.firebase.encoders.b y;
    public static final com.google.firebase.encoders.b z;
    public static final C3384r0 a = new C3384r0();
    public static final com.google.firebase.encoders.b b = new com.google.firebase.encoders.b("systemInfo", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(1))));
    public static final com.google.firebase.encoders.b c = new com.google.firebase.encoders.b("eventName", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(2))));
    public static final com.google.firebase.encoders.b d = new com.google.firebase.encoders.b("isThickClient", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(37))));
    public static final com.google.firebase.encoders.b e = new com.google.firebase.encoders.b("clientType", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(61))));
    public static final com.google.firebase.encoders.b f = new com.google.firebase.encoders.b("modelDownloadLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(3))));
    public static final com.google.firebase.encoders.b g = new com.google.firebase.encoders.b("customModelLoadLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(20))));
    public static final com.google.firebase.encoders.b h = new com.google.firebase.encoders.b("customModelInferenceLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(4))));
    public static final com.google.firebase.encoders.b i = new com.google.firebase.encoders.b("customModelCreateLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(29))));
    public static final com.google.firebase.encoders.b j = new com.google.firebase.encoders.b("onDeviceFaceDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(5))));
    public static final com.google.firebase.encoders.b k = new com.google.firebase.encoders.b("onDeviceFaceLoadLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(59))));
    public static final com.google.firebase.encoders.b l = new com.google.firebase.encoders.b("onDeviceTextDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(6))));
    public static final com.google.firebase.encoders.b m = new com.google.firebase.encoders.b("onDeviceBarcodeDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(7))));
    public static final com.google.firebase.encoders.b n = new com.google.firebase.encoders.b("onDeviceBarcodeLoadLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(58))));
    public static final com.google.firebase.encoders.b o = new com.google.firebase.encoders.b("onDeviceImageLabelCreateLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(48))));
    public static final com.google.firebase.encoders.b p = new com.google.firebase.encoders.b("onDeviceImageLabelLoadLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(49))));

    static {
        C3316a c3316a = new C3316a(18);
        HashMap map = new HashMap();
        map.put(B1.class, c3316a);
        q = new com.google.firebase.encoders.b("onDeviceImageLabelDetectionLogEvent", assistantMode.refactored.a.o(map));
        r = new com.google.firebase.encoders.b("onDeviceObjectCreateLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(26))));
        s = new com.google.firebase.encoders.b("onDeviceObjectLoadLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(27))));
        t = new com.google.firebase.encoders.b("onDeviceObjectInferenceLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(28))));
        u = new com.google.firebase.encoders.b("onDevicePoseDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(44))));
        v = new com.google.firebase.encoders.b("onDeviceSegmentationLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(45))));
        w = new com.google.firebase.encoders.b("onDeviceSmartReplyLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(19))));
        x = new com.google.firebase.encoders.b("onDeviceLanguageIdentificationLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(21))));
        C3316a c3316a2 = new C3316a(22);
        HashMap map2 = new HashMap();
        map2.put(B1.class, c3316a2);
        y = new com.google.firebase.encoders.b("onDeviceTranslationLogEvent", assistantMode.refactored.a.o(map2));
        z = new com.google.firebase.encoders.b("cloudFaceDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(8))));
        A = new com.google.firebase.encoders.b("cloudCropHintDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(9))));
        B = new com.google.firebase.encoders.b("cloudDocumentTextDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(10))));
        C = new com.google.firebase.encoders.b("cloudImagePropertiesDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(11))));
        D = new com.google.firebase.encoders.b("cloudImageLabelDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(12))));
        E = new com.google.firebase.encoders.b("cloudLandmarkDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(13))));
        F = new com.google.firebase.encoders.b("cloudLogoDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(14))));
        C3316a c3316a3 = new C3316a(15);
        HashMap map3 = new HashMap();
        map3.put(B1.class, c3316a3);
        G = new com.google.firebase.encoders.b("cloudSafeSearchDetectionLogEvent", assistantMode.refactored.a.o(map3));
        H = new com.google.firebase.encoders.b("cloudTextDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(16))));
        I = new com.google.firebase.encoders.b("cloudWebSearchDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(17))));
        J = new com.google.firebase.encoders.b("automlImageLabelingCreateLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(23))));
        K = new com.google.firebase.encoders.b("automlImageLabelingLoadLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(24))));
        L = new com.google.firebase.encoders.b("automlImageLabelingInferenceLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(25))));
        M = new com.google.firebase.encoders.b("isModelDownloadedLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(39))));
        N = new com.google.firebase.encoders.b("deleteModelLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(40))));
        C3316a c3316a4 = new C3316a(30);
        HashMap map4 = new HashMap();
        map4.put(B1.class, c3316a4);
        O = new com.google.firebase.encoders.b("aggregatedAutomlImageLabelingInferenceLogEvent", assistantMode.refactored.a.o(map4));
        P = new com.google.firebase.encoders.b("aggregatedCustomModelInferenceLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(31))));
        Q = new com.google.firebase.encoders.b("aggregatedOnDeviceFaceDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(32))));
        R = new com.google.firebase.encoders.b("aggregatedOnDeviceBarcodeDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(33))));
        S = new com.google.firebase.encoders.b("aggregatedOnDeviceImageLabelDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(34))));
        T = new com.google.firebase.encoders.b("aggregatedOnDeviceObjectInferenceLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(35))));
        U = new com.google.firebase.encoders.b("aggregatedOnDeviceTextDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(36))));
        V = new com.google.firebase.encoders.b("aggregatedOnDevicePoseDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(46))));
        C3316a c3316a5 = new C3316a(47);
        HashMap map5 = new HashMap();
        map5.put(B1.class, c3316a5);
        W = new com.google.firebase.encoders.b("aggregatedOnDeviceSegmentationLogEvent", assistantMode.refactored.a.o(map5));
        X = new com.google.firebase.encoders.b("pipelineAccelerationInferenceEvents", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(69))));
        Y = new com.google.firebase.encoders.b("remoteConfigLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(42))));
        Z = new com.google.firebase.encoders.b("inputImageConstructionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(50))));
        a0 = new com.google.firebase.encoders.b("leakedHandleEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(51))));
        b0 = new com.google.firebase.encoders.b("cameraSourceLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(52))));
        c0 = new com.google.firebase.encoders.b("imageLabelOptionalModuleLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(53))));
        d0 = new com.google.firebase.encoders.b("languageIdentificationOptionalModuleLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(54))));
        C3316a c3316a6 = new C3316a(60);
        HashMap map6 = new HashMap();
        map6.put(B1.class, c3316a6);
        e0 = new com.google.firebase.encoders.b("faceDetectionOptionalModuleLogEvent", assistantMode.refactored.a.o(map6));
        f0 = new com.google.firebase.encoders.b("nlClassifierOptionalModuleLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(55))));
        g0 = new com.google.firebase.encoders.b("nlClassifierClientLibraryLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(56))));
        h0 = new com.google.firebase.encoders.b("accelerationAllowlistLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(57))));
        i0 = new com.google.firebase.encoders.b("toxicityDetectionCreateEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(62))));
        j0 = new com.google.firebase.encoders.b("toxicityDetectionLoadEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(63))));
        k0 = new com.google.firebase.encoders.b("toxicityDetectionInferenceEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(64))));
        l0 = new com.google.firebase.encoders.b("barcodeDetectionOptionalModuleLogEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(65))));
        C3316a c3316a7 = new C3316a(66);
        HashMap map7 = new HashMap();
        map7.put(B1.class, c3316a7);
        m0 = new com.google.firebase.encoders.b("customImageLabelOptionalModuleLogEvent", assistantMode.refactored.a.o(map7));
        n0 = new com.google.firebase.encoders.b("codeScannerScanApiEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(67))));
        o0 = new com.google.firebase.encoders.b("codeScannerOptionalModuleEvent", assistantMode.refactored.a.o(AbstractC1642h.o(B1.class, new C3316a(68))));
    }

    @Override // com.google.firebase.encoders.a
    public final void a(Object obj, Object obj2) {
        C3323b2 c3323b2 = (C3323b2) obj;
        com.google.firebase.encoders.d dVar = (com.google.firebase.encoders.d) obj2;
        dVar.g(b, c3323b2.a);
        dVar.g(c, c3323b2.b);
        dVar.g(d, null);
        dVar.g(e, null);
        dVar.g(f, null);
        dVar.g(g, null);
        dVar.g(h, null);
        dVar.g(i, null);
        dVar.g(j, null);
        dVar.g(k, null);
        dVar.g(l, null);
        dVar.g(m, null);
        dVar.g(n, null);
        dVar.g(o, null);
        dVar.g(p, null);
        dVar.g(q, null);
        dVar.g(r, null);
        dVar.g(s, null);
        dVar.g(t, null);
        dVar.g(u, null);
        dVar.g(v, null);
        dVar.g(w, null);
        dVar.g(x, null);
        dVar.g(y, null);
        dVar.g(z, null);
        dVar.g(A, null);
        dVar.g(B, null);
        dVar.g(C, null);
        dVar.g(D, null);
        dVar.g(E, null);
        dVar.g(F, null);
        dVar.g(G, null);
        dVar.g(H, null);
        dVar.g(I, null);
        dVar.g(J, null);
        dVar.g(K, null);
        dVar.g(L, null);
        dVar.g(M, null);
        dVar.g(N, null);
        dVar.g(O, null);
        dVar.g(P, null);
        dVar.g(Q, null);
        dVar.g(R, null);
        dVar.g(S, null);
        dVar.g(T, null);
        dVar.g(U, null);
        dVar.g(V, null);
        dVar.g(W, null);
        dVar.g(X, null);
        dVar.g(Y, null);
        dVar.g(Z, null);
        dVar.g(a0, null);
        dVar.g(b0, c3323b2.c);
        dVar.g(c0, null);
        dVar.g(d0, null);
        dVar.g(e0, null);
        dVar.g(f0, null);
        dVar.g(g0, null);
        dVar.g(h0, null);
        dVar.g(i0, null);
        dVar.g(j0, null);
        dVar.g(k0, null);
        dVar.g(l0, null);
        dVar.g(m0, null);
        dVar.g(n0, null);
        dVar.g(o0, null);
    }
}
