package androidx.compose.material3.tokens;

import com.google.android.gms.internal.mlkit_vision_barcode.S5;

/* loaded from: classes.dex */
public abstract class E {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final androidx.compose.ui.text.font.u D;
    public static final androidx.compose.ui.text.font.w E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final androidx.compose.ui.text.font.u I;
    public static final androidx.compose.ui.text.font.w J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final androidx.compose.ui.text.font.u N;
    public static final androidx.compose.ui.text.font.w O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final androidx.compose.ui.text.font.u S;
    public static final androidx.compose.ui.text.font.w T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final androidx.compose.ui.text.font.u X;
    public static final androidx.compose.ui.text.font.w Y;
    public static final long Z;
    public static final androidx.compose.ui.text.font.w a;
    public static final long a0;
    public static final long b;
    public static final long b0;
    public static final long c;
    public static final androidx.compose.ui.text.font.u c0;
    public static final long d;
    public static final androidx.compose.ui.text.font.w d0;
    public static final androidx.compose.ui.text.font.u e;
    public static final long e0;
    public static final androidx.compose.ui.text.font.w f;
    public static final long f0;
    public static final long g;
    public static final long g0;
    public static final long h;
    public static final androidx.compose.ui.text.font.u h0;
    public static final long i;
    public static final androidx.compose.ui.text.font.w i0;
    public static final androidx.compose.ui.text.font.u j;
    public static final long j0;
    public static final androidx.compose.ui.text.font.w k;
    public static final long k0;
    public static final long l;
    public static final long l0;
    public static final long m;
    public static final androidx.compose.ui.text.font.u m0;
    public static final long n;
    public static final androidx.compose.ui.text.font.w n0;
    public static final androidx.compose.ui.text.font.u o;
    public static final long o0;
    public static final androidx.compose.ui.text.font.w p;
    public static final long p0;
    public static final long q;
    public static final long q0;
    public static final long r;
    public static final androidx.compose.ui.text.font.u r0;
    public static final long s;
    public static final androidx.compose.ui.text.font.w s0;
    public static final androidx.compose.ui.text.font.u t;
    public static final long t0;
    public static final androidx.compose.ui.text.font.w u;
    public static final long u0;
    public static final long v;
    public static final long v0;
    public static final long w;
    public static final androidx.compose.ui.text.font.u w0;
    public static final long x;
    public static final androidx.compose.ui.text.font.u y;
    public static final androidx.compose.ui.text.font.w z;

    static {
        androidx.compose.ui.text.font.u uVar = F.a;
        androidx.compose.ui.text.font.w wVar = androidx.compose.ui.text.font.j.b;
        a = wVar;
        b = S5.f(24.0d);
        c = S5.g(16);
        d = S5.f(0.5d);
        androidx.compose.ui.text.font.u uVar2 = F.b;
        e = uVar2;
        f = wVar;
        g = S5.f(20.0d);
        h = S5.g(14);
        i = S5.f(0.2d);
        j = uVar2;
        k = wVar;
        l = S5.f(16.0d);
        m = S5.g(12);
        n = S5.f(0.4d);
        o = uVar2;
        p = wVar;
        q = S5.f(64.0d);
        r = S5.g(57);
        long jF = S5.f(0.2d);
        if (S5.h(jF)) {
            throw new IllegalArgumentException("Cannot perform operation for Unspecified type.");
        }
        s = S5.i(jF & 1095216660480L, -androidx.compose.ui.unit.m.c(jF));
        t = uVar2;
        u = wVar;
        v = S5.f(52.0d);
        w = S5.g(45);
        x = S5.f(0.0d);
        y = uVar2;
        z = wVar;
        A = S5.f(44.0d);
        B = S5.g(36);
        C = S5.f(0.0d);
        D = uVar2;
        E = wVar;
        F = S5.f(40.0d);
        G = S5.g(32);
        H = S5.f(0.0d);
        I = uVar2;
        J = wVar;
        K = S5.f(36.0d);
        L = S5.g(28);
        M = S5.f(0.0d);
        N = uVar2;
        O = wVar;
        P = S5.f(32.0d);
        Q = S5.g(24);
        R = S5.f(0.0d);
        S = uVar2;
        T = wVar;
        U = S5.f(20.0d);
        V = S5.g(14);
        W = S5.f(0.1d);
        androidx.compose.ui.text.font.u uVar3 = F.a;
        X = uVar3;
        Y = wVar;
        Z = S5.f(16.0d);
        a0 = S5.g(12);
        b0 = S5.f(0.5d);
        c0 = uVar3;
        d0 = wVar;
        e0 = S5.f(16.0d);
        f0 = S5.g(11);
        g0 = S5.f(0.5d);
        h0 = uVar3;
        i0 = wVar;
        j0 = S5.f(28.0d);
        k0 = S5.g(22);
        l0 = S5.f(0.0d);
        m0 = uVar2;
        n0 = wVar;
        o0 = S5.f(24.0d);
        p0 = S5.g(16);
        q0 = S5.f(0.2d);
        r0 = uVar3;
        s0 = wVar;
        t0 = S5.f(20.0d);
        u0 = S5.g(14);
        v0 = S5.f(0.1d);
        w0 = uVar3;
    }
}
