package androidx.compose.material3.tokens;

import com.comscore.streaming.AdvertisementType;
import com.comscore.streaming.ContentType;
import com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView;
import com.google.android.gms.dynamite.descriptors.com.google.android.gms.measurement.dynamite.ModuleDescriptor;
import com.onetrust.otpublishers.headless.Public.OTUIDisplayReason.OTUIDisplayReasonCode;

/* loaded from: classes.dex */
public abstract class t {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final /* synthetic */ int X = 0;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        androidx.compose.ui.graphics.F.e(0, 0, 0);
        androidx.compose.ui.graphics.F.e(0, 0, 0);
        a = androidx.compose.ui.graphics.F.e(65, 14, 11);
        b = androidx.compose.ui.graphics.F.e(255, 255, 255);
        c = androidx.compose.ui.graphics.F.e(96, 20, 16);
        d = androidx.compose.ui.graphics.F.e(140, 29, 24);
        e = androidx.compose.ui.graphics.F.e(179, 38, 30);
        androidx.compose.ui.graphics.F.e(220, 54, 46);
        androidx.compose.ui.graphics.F.e(228, OTUIDisplayReasonCode.UIShownCode.BANNER_SHOWN_CONSENT_EXPIRED, 98);
        androidx.compose.ui.graphics.F.e(236, 146, 142);
        androidx.compose.ui.graphics.F.e(242, 184, 181);
        f = androidx.compose.ui.graphics.F.e(249, 222, 220);
        androidx.compose.ui.graphics.F.e(252, 238, 238);
        androidx.compose.ui.graphics.F.e(255, 251, 249);
        g = androidx.compose.ui.graphics.F.e(0, 0, 0);
        h = androidx.compose.ui.graphics.F.e(29, 27, 32);
        i = androidx.compose.ui.graphics.F.e(255, 255, 255);
        j = androidx.compose.ui.graphics.F.e(33, 31, 38);
        k = androidx.compose.ui.graphics.F.e(43, 41, 48);
        l = androidx.compose.ui.graphics.F.e(50, 47, 53);
        m = androidx.compose.ui.graphics.F.e(54, 52, 59);
        n = androidx.compose.ui.graphics.F.e(59, 56, 62);
        androidx.compose.ui.graphics.F.e(72, 70, 76);
        o = androidx.compose.ui.graphics.F.e(15, 13, 19);
        androidx.compose.ui.graphics.F.e(96, 93, 100);
        androidx.compose.ui.graphics.F.e(ContentType.USER_GENERATED_SHORT_FORM_ON_DEMAND, 118, 125);
        p = androidx.compose.ui.graphics.F.e(20, 18, 24);
        androidx.compose.ui.graphics.F.e(147, 143, 150);
        androidx.compose.ui.graphics.F.e(174, 169, 177);
        androidx.compose.ui.graphics.F.e(202, 197, 205);
        q = androidx.compose.ui.graphics.F.e(222, 216, 225);
        r = androidx.compose.ui.graphics.F.e(230, 224, AdvertisementType.BRANDED_ON_DEMAND_POST_ROLL);
        s = androidx.compose.ui.graphics.F.e(236, 230, 240);
        t = androidx.compose.ui.graphics.F.e(243, 237, 247);
        u = androidx.compose.ui.graphics.F.e(245, 239, 247);
        v = androidx.compose.ui.graphics.F.e(247, 242, 250);
        w = androidx.compose.ui.graphics.F.e(254, 247, 255);
        androidx.compose.ui.graphics.F.e(255, 251, 255);
        androidx.compose.ui.graphics.F.e(0, 0, 0);
        androidx.compose.ui.graphics.F.e(29, 26, 34);
        androidx.compose.ui.graphics.F.e(255, 255, 255);
        androidx.compose.ui.graphics.F.e(50, 47, 55);
        x = androidx.compose.ui.graphics.F.e(73, 69, 79);
        androidx.compose.ui.graphics.F.e(96, 93, 102);
        y = androidx.compose.ui.graphics.F.e(ContentType.USER_GENERATED_SHORT_FORM_ON_DEMAND, 116, 126);
        z = androidx.compose.ui.graphics.F.e(147, 143, 153);
        androidx.compose.ui.graphics.F.e(174, 169, SubsamplingScaleImageView.ORIENTATION_180);
        A = androidx.compose.ui.graphics.F.e(202, 196, OTUIDisplayReasonCode.UIShownCode.PC_SHOWN_BACKWARD_COMPATIBILITY);
        B = androidx.compose.ui.graphics.F.e(AdvertisementType.BRANDED_ON_DEMAND_PRE_ROLL, 224, 236);
        androidx.compose.ui.graphics.F.e(245, 238, 250);
        androidx.compose.ui.graphics.F.e(255, 251, 254);
        androidx.compose.ui.graphics.F.e(0, 0, 0);
        C = androidx.compose.ui.graphics.F.e(33, 0, 93);
        D = androidx.compose.ui.graphics.F.e(255, 255, 255);
        E = androidx.compose.ui.graphics.F.e(56, 30, 114);
        F = androidx.compose.ui.graphics.F.e(79, 55, 139);
        G = androidx.compose.ui.graphics.F.e(103, 80, 164);
        androidx.compose.ui.graphics.F.e(127, 103, 190);
        androidx.compose.ui.graphics.F.e(154, 130, 219);
        androidx.compose.ui.graphics.F.e(182, 157, 248);
        H = androidx.compose.ui.graphics.F.e(OTUIDisplayReasonCode.UIShownCode.PC_SHOWN_BACKWARD_COMPATIBILITY, 188, 255);
        I = androidx.compose.ui.graphics.F.e(AdvertisementType.BRANDED_AS_CONTENT, AdvertisementType.LIVE, 255);
        androidx.compose.ui.graphics.F.e(246, 237, 255);
        androidx.compose.ui.graphics.F.e(255, 251, 254);
        androidx.compose.ui.graphics.F.e(0, 0, 0);
        J = androidx.compose.ui.graphics.F.e(29, 25, 43);
        K = androidx.compose.ui.graphics.F.e(255, 255, 255);
        L = androidx.compose.ui.graphics.F.e(51, 45, 65);
        M = androidx.compose.ui.graphics.F.e(74, 68, 88);
        N = androidx.compose.ui.graphics.F.e(98, 91, ContentType.LIVE);
        androidx.compose.ui.graphics.F.e(ContentType.USER_GENERATED_LONG_FORM_ON_DEMAND, 114, 137);
        androidx.compose.ui.graphics.F.e(149, ModuleDescriptor.MODULE_VERSION, 165);
        androidx.compose.ui.graphics.F.e(176, 167, 192);
        O = androidx.compose.ui.graphics.F.e(204, 194, 220);
        P = androidx.compose.ui.graphics.F.e(AdvertisementType.BRANDED_ON_DEMAND_MID_ROLL, 222, 248);
        androidx.compose.ui.graphics.F.e(246, 237, 255);
        androidx.compose.ui.graphics.F.e(255, 251, 254);
        androidx.compose.ui.graphics.F.e(0, 0, 0);
        Q = androidx.compose.ui.graphics.F.e(49, 17, 29);
        R = androidx.compose.ui.graphics.F.e(255, 255, 255);
        S = androidx.compose.ui.graphics.F.e(73, 37, 50);
        T = androidx.compose.ui.graphics.F.e(99, 59, 72);
        U = androidx.compose.ui.graphics.F.e(125, 82, 96);
        androidx.compose.ui.graphics.F.e(152, OTUIDisplayReasonCode.UIShownCode.BANNER_SHOWN_CONSENT_EXPIRED, 119);
        androidx.compose.ui.graphics.F.e(181, 131, 146);
        androidx.compose.ui.graphics.F.e(OTUIDisplayReasonCode.UIShownCode.PC_SHOWN_SHOW_PC_CALLED, 157, 172);
        V = androidx.compose.ui.graphics.F.e(239, 184, 200);
        W = androidx.compose.ui.graphics.F.e(255, 216, 228);
        androidx.compose.ui.graphics.F.e(255, 236, 241);
        androidx.compose.ui.graphics.F.e(255, 251, 250);
        androidx.compose.ui.graphics.F.e(255, 255, 255);
    }
}
