package com.onetrust.otpublishers.headless.UI.UIProperty;

import androidx.camera.camera2.internal.c0;
import androidx.constraintlayout.motion.widget.n;
import androidx.navigation.internal.m;
import com.google.android.gms.internal.mlkit_vision_document_scanner.AbstractC3633h4;

/* loaded from: classes2.dex */
public final class e {
    public String C;
    public String I;
    public String J;
    public String K;
    public boolean L;
    public String a;
    public String b;
    public String c;
    public String d;
    public String e;
    public boolean f;
    public String g;
    public String h;
    public boolean i;
    public boolean j = true;
    public m k = new m();
    public m l = new m();
    public m m = new m();
    public m n = new m();
    public m o = new m();
    public m p = new m();
    public m q = new m();
    public m r = new m();
    public m s = new m();
    public m t = new m();
    public m u = new m();
    public m v = new m();
    public n w = new n();
    public n x = new n();
    public n y = new n();
    public c0 z = new c0(13);
    public com.google.android.gms.internal.appset.e A = new com.google.android.gms.internal.appset.e(10, false);
    public final c0 B = new c0(14, false);
    public com.quizlet.data.repository.user.e D = new com.quizlet.data.repository.user.e();
    public com.quizlet.data.repository.user.e E = new com.quizlet.data.repository.user.e();
    public com.quizlet.data.repository.user.e F = new com.quizlet.data.repository.user.e();
    public final androidx.camera.camera2.internal.compat.workaround.b G = new androidx.camera.camera2.internal.compat.workaround.b();
    public final boolean H = true;

    public final String toString() {
        StringBuilder sb = new StringBuilder("OTPCUIProperty{backgroundColor='");
        sb.append(this.a);
        sb.append("', lineBreakColor='");
        sb.append(this.b);
        sb.append("', toggleThumbColorOn='");
        sb.append(this.c);
        sb.append("', toggleThumbColorOff='");
        sb.append(this.d);
        sb.append("', toggleTrackColor='");
        sb.append(this.e);
        sb.append("', showLogoOnPC=");
        sb.append(this.f);
        sb.append(", showOTLogo=");
        sb.append(this.i);
        sb.append(", lineBreakShow='null', savePreferencesUnderline='null', pageHeaderTitle='null', rightChevronColor='");
        sb.append(this.g);
        sb.append("', summaryTitleTextProperty=");
        AbstractC3633h4.a(this.k, sb, ", summaryTitleDescriptionTextProperty=");
        AbstractC3633h4.a(this.l, sb, ", dsIdTitleTextProperty=");
        AbstractC3633h4.a(this.m, sb, ", dsIdTextProperty=");
        AbstractC3633h4.a(this.n, sb, ", dsIdDescriptionTextProperty=");
        AbstractC3633h4.a(this.r, sb, ", purposeTitleTextProperty=");
        AbstractC3633h4.a(this.s, sb, ", purposeItemTextProperty=");
        AbstractC3633h4.a(this.t, sb, ", alwaysActiveTextProperty=");
        AbstractC3633h4.a(this.u, sb, ", acceptAllButtonProperty=");
        sb.append(this.w.toString());
        sb.append(", rejectAllButtonProperty=");
        sb.append(this.x.toString());
        sb.append(", confirmMyChoiceProperty=");
        sb.append(this.y.toString());
        sb.append(", closeButtonProperty=");
        sb.append(this.z.toString());
        sb.append(", logoProperty=");
        sb.append(this.A.toString());
        sb.append(", menuProperty=");
        sb.append(this.B.toString());
        sb.append(", backButtonColor='");
        sb.append(this.C);
        sb.append("', policyLinkProperty=");
        sb.append(this.D.toString());
        sb.append(", vendorSdkTitleTextProperty=");
        AbstractC3633h4.a(this.v, sb, ", vendorListLinkProperty=");
        sb.append(this.E.toString());
        sb.append(", sdkListLinkProperty=");
        sb.append(this.F.toString());
        sb.append(", applyUIProperty=");
        sb.append(this.H);
        sb.append(", dsIdShow='");
        sb.append(this.I);
        sb.append("', dsIdDescriptionShow='");
        sb.append(this.J);
        sb.append("', dsIdShowDividerBar=");
        return android.support.v4.media.session.a.u(sb, this.L, '}');
    }
}
