package androidx.webkit.internal;

/* loaded from: classes.dex */
public abstract class s {
    public static final b a;
    public static final b b;
    public static final b c;
    public static final b d;
    public static final b e;
    public static final b f;
    public static final b g;

    static {
        new b(0, "VISUAL_STATE_CALLBACK", "VISUAL_STATE_CALLBACK");
        new b(0, "OFF_SCREEN_PRERASTER", "OFF_SCREEN_PRERASTER");
        new b(3, "SAFE_BROWSING_ENABLE", "SAFE_BROWSING_ENABLE");
        new b(1, "DISABLED_ACTION_MODE_MENU_ITEMS", "DISABLED_ACTION_MODE_MENU_ITEMS");
        new b(4, "START_SAFE_BROWSING", "START_SAFE_BROWSING");
        new b(4, "SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_WHITELIST");
        new b(4, "SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_ALLOWLIST");
        new b(4, "SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_WHITELIST");
        new b(4, "SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_ALLOWLIST");
        new b(4, "SAFE_BROWSING_PRIVACY_POLICY_URL", "SAFE_BROWSING_PRIVACY_POLICY_URL");
        new b(1, "SERVICE_WORKER_BASIC_USAGE", "SERVICE_WORKER_BASIC_USAGE");
        new b(1, "SERVICE_WORKER_CACHE_MODE", "SERVICE_WORKER_CACHE_MODE");
        new b(1, "SERVICE_WORKER_CONTENT_ACCESS", "SERVICE_WORKER_CONTENT_ACCESS");
        new b(1, "SERVICE_WORKER_FILE_ACCESS", "SERVICE_WORKER_FILE_ACCESS");
        new b(1, "SERVICE_WORKER_BLOCK_NETWORK_LOADS", "SERVICE_WORKER_BLOCK_NETWORK_LOADS");
        new b(1, "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST", "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST");
        new b(0, "RECEIVE_WEB_RESOURCE_ERROR", "RECEIVE_WEB_RESOURCE_ERROR");
        new b(0, "RECEIVE_HTTP_ERROR", "RECEIVE_HTTP_ERROR");
        new b(1, "SHOULD_OVERRIDE_WITH_REDIRECTS", "SHOULD_OVERRIDE_WITH_REDIRECTS");
        new b(4, "SAFE_BROWSING_HIT", "SAFE_BROWSING_HIT");
        new b(1, "WEB_RESOURCE_REQUEST_IS_REDIRECT", "WEB_RESOURCE_REQUEST_IS_REDIRECT");
        new b(0, "WEB_RESOURCE_ERROR_GET_DESCRIPTION", "WEB_RESOURCE_ERROR_GET_DESCRIPTION");
        new b(0, "WEB_RESOURCE_ERROR_GET_CODE", "WEB_RESOURCE_ERROR_GET_CODE");
        new b(4, "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY", "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY");
        new b(4, "SAFE_BROWSING_RESPONSE_PROCEED", "SAFE_BROWSING_RESPONSE_PROCEED");
        new b(4, "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL", "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL");
        new b(0, "WEB_MESSAGE_PORT_POST_MESSAGE", "WEB_MESSAGE_PORT_POST_MESSAGE");
        new b(0, "WEB_MESSAGE_PORT_CLOSE", "WEB_MESSAGE_PORT_CLOSE");
        a = new b(2, "WEB_MESSAGE_ARRAY_BUFFER", "WEB_MESSAGE_ARRAY_BUFFER");
        new b(0, "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK", "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK");
        new b(0, "CREATE_WEB_MESSAGE_CHANNEL", "CREATE_WEB_MESSAGE_CHANNEL");
        new b(0, "POST_WEB_MESSAGE", "POST_WEB_MESSAGE");
        new b(0, "WEB_MESSAGE_CALLBACK_ON_MESSAGE", "WEB_MESSAGE_CALLBACK_ON_MESSAGE");
        new b(3, "GET_WEB_VIEW_CLIENT", "GET_WEB_VIEW_CLIENT");
        new b(3, "GET_WEB_CHROME_CLIENT", "GET_WEB_CHROME_CLIENT");
        new b(6, "GET_WEB_VIEW_RENDERER", "GET_WEB_VIEW_RENDERER");
        new b(6, "WEB_VIEW_RENDERER_TERMINATE", "WEB_VIEW_RENDERER_TERMINATE");
        new b(5, "TRACING_CONTROLLER_BASIC_USAGE", "TRACING_CONTROLLER_BASIC_USAGE");
        new o();
        new o();
        new b(6, "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE", "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE");
        new q();
        new b(2, "PROXY_OVERRIDE", "PROXY_OVERRIDE:3");
        b = new b(2, "MULTI_PROCESS", "MULTI_PROCESS_QUERY");
        c = new b(6, "FORCE_DARK", "FORCE_DARK");
        d = new b(2, "FORCE_DARK_STRATEGY", "FORCE_DARK_BEHAVIOR");
        e = new b(2, "WEB_MESSAGE_LISTENER", "WEB_MESSAGE_LISTENER");
        f = new b(2, "DOCUMENT_START_SCRIPT", "DOCUMENT_START_SCRIPT:1");
        new b(2, "PROXY_OVERRIDE_REVERSE_BYPASS", "PROXY_OVERRIDE_REVERSE_BYPASS");
        new b(2, "GET_VARIATIONS_HEADER", "GET_VARIATIONS_HEADER");
        new b(2, "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY", "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY");
        new b(2, "GET_COOKIE_INFO", "GET_COOKIE_INFO");
        new b(2, "REQUESTED_WITH_HEADER_ALLOW_LIST", "REQUESTED_WITH_HEADER_ALLOW_LIST");
        new b(2, "USER_AGENT_METADATA", "USER_AGENT_METADATA");
        new r(2, "MULTI_PROFILE", "MULTI_PROFILE");
        new b(2, "ATTRIBUTION_REGISTRATION_BEHAVIOR", "ATTRIBUTION_BEHAVIOR");
        new b(2, "WEBVIEW_MEDIA_INTEGRITY_API_STATUS", "WEBVIEW_INTEGRITY_API_STATUS");
        g = new b(2, "MUTE_AUDIO", "MUTE_AUDIO");
    }

    public static UnsupportedOperationException a() {
        return new UnsupportedOperationException("This method is not supported by the current version of the framework and the current WebView APK");
    }
}
