package com.google.android.gms.measurement.internal;

import com.pubmatic.sdk.video.c;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;

/* renamed from: com.google.android.gms.measurement.internal.t, reason: case insensitive filesystem */
/* loaded from: classes2.dex */
public abstract class AbstractC3893t {
    public static final C3891s A;
    public static final C3891s A0;
    public static final C3891s B;
    public static final C3891s B0;
    public static final C3891s C;
    public static final C3891s C0;
    public static final C3891s D;
    public static final C3891s D0;
    public static final C3891s E;
    public static final C3891s E0;
    public static final C3891s F;
    public static final C3891s F0;
    public static final C3891s G;
    public static final C3891s G0;
    public static final C3891s H;
    public static final C3891s H0;
    public static final C3891s I;
    public static final C3891s I0;
    public static final C3891s J;
    public static final C3891s J0;
    public static final C3891s K;
    public static final C3891s K0;
    public static final C3891s L;
    public static final C3891s L0;
    public static final C3891s M;
    public static final C3891s M0;
    public static final C3891s N;
    public static final C3891s N0;
    public static final C3891s O;
    public static final C3891s O0;
    public static final C3891s P;
    public static final C3891s P0;
    public static final C3891s Q;
    public static final C3891s Q0;
    public static final C3891s R;
    public static final C3891s R0;
    public static final C3891s S;
    public static final C3891s S0;
    public static final C3891s T;
    public static final C3891s T0;
    public static final C3891s U;
    public static final C3891s U0;
    public static final C3891s V;
    public static final C3891s V0;
    public static final C3891s W;
    public static final C3891s W0;
    public static final C3891s X;
    public static final C3891s X0;
    public static final C3891s Y;
    public static final C3891s Y0;
    public static final C3891s Z;
    public static final C3891s Z0;
    public static final List a = Collections.synchronizedList(new ArrayList());
    public static final C3891s a0;
    public static final C3891s a1;
    public static final C3891s b;
    public static final C3891s b0;
    public static final C3891s b1;
    public static final C3891s c;
    public static final C3891s c0;
    public static final C3891s c1;
    public static final C3891s d;
    public static final C3891s d0;
    public static final C3891s d1;
    public static final C3891s e;
    public static final C3891s e0;
    public static final C3891s e1;
    public static final C3891s f;
    public static final C3891s f0;
    public static final C3891s f1;
    public static final C3891s g;
    public static final C3891s g0;
    public static final C3891s g1;
    public static final C3891s h;
    public static final C3891s h0;
    public static final C3891s h1;
    public static final C3891s i;
    public static final C3891s i0;
    public static final C3891s i1;
    public static final C3891s j;
    public static final C3891s j0;
    public static final C3891s j1;
    public static final C3891s k;
    public static final C3891s k0;
    public static final C3891s k1;
    public static final C3891s l;
    public static final C3891s l0;
    public static final C3891s l1;
    public static final C3891s m;
    public static final C3891s m0;
    public static final C3891s m1;
    public static final C3891s n;
    public static final C3891s n0;
    public static final C3891s n1;
    public static final C3891s o;
    public static final C3891s o0;
    public static final C3891s o1;
    public static final C3891s p;
    public static final C3891s p0;
    public static final C3891s p1;
    public static final C3891s q;
    public static final C3891s q0;
    public static final C3891s q1;
    public static final C3891s r;
    public static final C3891s r0;
    public static final C3891s r1;
    public static final C3891s s;
    public static final C3891s s0;
    public static final C3891s t;
    public static final C3891s t0;
    public static final C3891s u;
    public static final C3891s u0;
    public static final C3891s v;
    public static final C3891s v0;
    public static final C3891s w;
    public static final C3891s w0;
    public static final C3891s x;
    public static final C3891s x0;
    public static final C3891s y;
    public static final C3891s y0;
    public static final C3891s z;
    public static final C3891s z0;

    static {
        Collections.synchronizedSet(new HashSet());
        b = a("measurement.ad_id_cache_time", 10000L, new com.google.mlkit.common.sdkinternal.model.a(12), false);
        c = a("measurement.app_uninstalled_additional_ad_id_cache_time", 3600000L, new com.quizlet.shared.usecase.folderstudymaterials.a(13), false);
        d = a("measurement.monitoring.sample_period_millis", 86400000L, new com.google.mlkit.common.internal.model.a(14), false);
        e = a("measurement.config.cache_time", 86400000L, new com.google.android.gms.internal.mlkit_common.u(15), false);
        f = a("measurement.config.url_scheme", "https", new com.quizlet.shared.usecase.srs.a(15), false);
        g = a("measurement.config.url_authority", "app-measurement.com", new com.quizlet.shared.usecase.folderstudymaterials.b(16), false);
        h = a("measurement.upload.max_bundles", 100, new com.google.mlkit.common.sdkinternal.b(17), false);
        i = a("measurement.upload.max_batch_size", 65536, new com.google.mlkit.common.sdkinternal.b(10), false);
        j = a("measurement.upload.max_bundle_size", 65536, new com.google.android.material.shape.e(11), false);
        k = a("measurement.upload.max_events_per_bundle", 1000, new com.quizlet.shared.usecase.studiableMetadata.a(11), false);
        l = a("measurement.upload.max_events_per_day", 100000, new retrofit2.adapter.rxjava3.d(11), false);
        m = a("measurement.upload.max_error_events_per_day", 1000, new com.quizlet.shared.usecase.folderstudymaterials.c(12), false);
        n = a("measurement.upload.max_public_events_per_day", 50000, new assistantMode.utils.studiableMetadata.b(13), false);
        o = a("measurement.upload.max_conversions_per_day", Integer.valueOf(c.a.DEFAULT_MEDIA_URI_TIMEOUT), new com.google.android.gms.internal.mlkit_common.u(13), false);
        p = a("measurement.upload.max_realtime_events_per_day", 10, new com.google.firebase.heartbeatinfo.e(13), false);
        q = a("measurement.store.max_stored_events_per_app", 100000, new com.google.firebase.perf.logging.b(13), false);
        r = a("measurement.upload.url", "https://app-measurement.com/a", new com.google.mlkit.common.internal.model.a(13), false);
        s = a("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d", new com.google.mlkit.common.sdkinternal.b(13), false);
        t = a("measurement.sgtm.service_upload_apps_list", "", new com.google.mlkit.common.sdkinternal.model.a(13), false);
        u = a("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504", new com.onetrust.otpublishers.headless.Internal.Helper.h(13), false);
        v = a("measurement.sgtm.upload.retry_interval", 600000L, new com.quizlet.shared.usecase.folderstudymaterials.b(13), false);
        w = a("measurement.sgtm.upload.retry_max_wait", 21600000L, new com.quizlet.shared.usecase.folderstudymaterials.c(13), false);
        x = a("measurement.sgtm.batch.retry_interval", 1800000L, new com.quizlet.shared.usecase.folderstudymaterials.d(13), false);
        y = a("measurement.sgtm.batch.retry_max_wait", 21600000L, new com.quizlet.shared.usecase.studiableMetadata.a(13), false);
        z = a("measurement.sgtm.batch.retry_max_count", 10, new retrofit2.adapter.rxjava3.d(13), false);
        A = a("measurement.sgtm.upload.max_queued_batches", 5000, new assistantMode.utils.studiableMetadata.b(14), false);
        B = a("measurement.sgtm.upload.batches_retrieval_limit", 5, new com.google.android.gms.internal.mlkit_common.u(14), false);
        C = a("measurement.sgtm.upload.min_delay_after_startup", 5000L, new com.google.android.material.shape.e(14), false);
        D = a("measurement.sgtm.upload.min_delay_after_broadcast", 1000L, new com.google.firebase.heartbeatinfo.e(14), false);
        E = a("measurement.sgtm.upload.min_delay_after_background", 600000L, new com.google.firebase.perf.logging.b(14), false);
        F = a("measurement.upload.backoff_period", 43200000L, new com.google.mlkit.common.sdkinternal.b(14), false);
        a("measurement.upload.window_interval", 3600000L, new com.google.mlkit.common.sdkinternal.model.a(14), false);
        G = a("measurement.upload.interval", 3600000L, new com.quizlet.shared.usecase.folderstudymaterials.a(14), false);
        H = a("measurement.upload.realtime_upload_interval", 10000L, new com.quizlet.shared.usecase.folderstudymaterials.b(14), false);
        I = a("measurement.upload.debug_upload_interval", 1000L, new com.quizlet.shared.usecase.folderstudymaterials.c(14), false);
        J = a("measurement.upload.minimum_delay", 500L, new com.quizlet.shared.usecase.folderstudymaterials.d(14), false);
        K = a("measurement.alarm_manager.minimum_interval", 60000L, new com.quizlet.shared.usecase.srs.a(14), false);
        L = a("measurement.upload.stale_data_deletion_interval", 86400000L, new com.quizlet.shared.usecase.studiableMetadata.a(14), false);
        M = a("measurement.upload.refresh_blacklisted_config_interval", 604800000L, new retrofit2.adapter.rxjava3.d(14), false);
        N = a("measurement.upload.initial_upload_delay_time", 15000L, new assistantMode.utils.studiableMetadata.b(15), false);
        O = a("measurement.upload.retry_time", 1800000L, new com.google.android.material.shape.e(15), false);
        P = a("measurement.upload.retry_count", 6, new com.google.firebase.perf.logging.b(15), false);
        Q = a("measurement.upload.max_queue_time", 518400000L, new com.google.mlkit.common.internal.model.a(15), false);
        R = a("measurement.upload.google_signal_max_queue_time", 300000L, new com.google.mlkit.common.sdkinternal.b(15), false);
        S = a("measurement.lifetimevalue.max_currency_tracked", 4, new com.google.mlkit.common.sdkinternal.model.a(15), false);
        T = a("measurement.audience.filter_result_max_count", 200, new com.onetrust.otpublishers.headless.Internal.Helper.h(15), false);
        U = a("measurement.upload.max_public_user_properties", 100, null, false);
        V = a("measurement.upload.max_event_name_cardinality", 2000, null, false);
        W = a("measurement.upload.max_public_event_params", 100, null, false);
        X = a("measurement.service_client.idle_disconnect_millis", 5000L, new com.quizlet.shared.usecase.folderstudymaterials.a(15), false);
        Y = a("measurement.service_client.reconnect_millis", 1000L, new com.quizlet.shared.usecase.folderstudymaterials.b(15), false);
        Boolean bool = Boolean.FALSE;
        Z = a("measurement.test.boolean_flag", bool, new com.quizlet.shared.usecase.folderstudymaterials.c(15), false);
        a0 = a("measurement.test.string_flag", "---", new com.quizlet.shared.usecase.folderstudymaterials.d(15), false);
        b0 = a("measurement.test.long_flag", -1L, new retrofit2.adapter.rxjava3.d(15), false);
        a("measurement.test.cached_long_flag", -1L, new assistantMode.utils.studiableMetadata.b(16), true);
        c0 = a("measurement.test.int_flag", -2, new com.google.android.gms.internal.mlkit_common.u(16), false);
        d0 = a("measurement.test.double_flag", Double.valueOf(-3.0d), new com.google.android.material.shape.e(16), false);
        e0 = a("measurement.experiment.max_ids", 50, new com.google.firebase.heartbeatinfo.e(16), false);
        f0 = a("measurement.upload.max_item_scoped_custom_parameters", 27, new com.google.firebase.perf.logging.b(16), false);
        g0 = a("measurement.upload.max_event_parameter_value_length", Integer.valueOf(com.pubmatic.sdk.video.a.GENERAL_NONLINEAR_AD_ERROR), new com.google.mlkit.common.internal.model.a(16), true);
        h0 = a("measurement.max_bundles_per_iteration", 100, new com.google.mlkit.common.sdkinternal.b(16), false);
        i0 = a("measurement.sdk.attribution.cache.ttl", 604800000L, new com.google.mlkit.common.sdkinternal.model.a(16), false);
        j0 = a("measurement.redaction.app_instance_id.ttl", 7200000L, new com.onetrust.otpublishers.headless.Internal.Helper.h(16), false);
        k0 = a("measurement.rb.attribution.client.min_ad_services_version", 7, new com.quizlet.shared.usecase.folderstudymaterials.c(16), false);
        l0 = a("measurement.dma_consent.max_daily_dcu_realtime_events", 1, new com.quizlet.shared.usecase.folderstudymaterials.d(16), false);
        m0 = a("measurement.rb.attribution.uri_scheme", "https", new com.quizlet.shared.usecase.srs.a(16), false);
        n0 = a("measurement.rb.attribution.uri_authority", "google-analytics.com", new com.quizlet.shared.usecase.studiableMetadata.a(16), false);
        o0 = a("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion", new retrofit2.adapter.rxjava3.d(16), false);
        p0 = a("measurement.session.engagement_interval", 3600000L, new assistantMode.utils.studiableMetadata.b(17), false);
        q0 = a("measurement.rb.attribution.app_allowlist", "*", new com.google.android.gms.internal.mlkit_common.u(17), false);
        r0 = a("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot", new com.google.android.material.shape.e(17), false);
        s0 = a("measurement.rb.attribution.event_params", "value|currency", new com.google.firebase.heartbeatinfo.e(17), false);
        t0 = a("measurement.rb.attribution.query_parameters_to_remove", "", new com.google.mlkit.common.internal.model.a(17), false);
        u0 = a("measurement.rb.attribution.max_queue_time", 864000000L, new com.google.mlkit.common.sdkinternal.model.a(17), false);
        v0 = a("measurement.rb.attribution.max_retry_delay_seconds", 16, new com.onetrust.otpublishers.headless.Internal.Helper.h(17), false);
        w0 = a("measurement.rb.attribution.client.min_time_after_boot_seconds", 90, new com.quizlet.shared.usecase.folderstudymaterials.a(17), false);
        a("measurement.rb.attribution.max_trigger_uris_queried_at_once", 0, new com.quizlet.shared.usecase.folderstudymaterials.b(17), false);
        x0 = a("measurement.rb.max_trigger_registrations_per_day", 1000, new com.quizlet.shared.usecase.folderstudymaterials.c(17), false);
        Boolean bool2 = Boolean.TRUE;
        y0 = a("measurement.config.bundle_for_all_apps_on_backgrounded", bool2, new com.quizlet.shared.usecase.folderstudymaterials.d(17), false);
        z0 = a("measurement.config.notify_trigger_uris_on_backgrounded", bool2, new com.quizlet.shared.usecase.srs.a(17), false);
        A0 = a("measurement.rb.attribution.notify_app_delay_millis", 3000, new com.quizlet.shared.usecase.studiableMetadata.a(17), false);
        B0 = a("measurement.quality.checksum", bool, null, false);
        C0 = a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, new com.google.firebase.perf.logging.b(10), false);
        D0 = a("measurement.audience.refresh_event_count_filters_timestamp", bool, new com.google.mlkit.common.internal.model.a(10), false);
        E0 = a("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, new com.google.mlkit.common.sdkinternal.model.a(10), true);
        F0 = a("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, new com.onetrust.otpublishers.headless.Internal.Helper.h(10), false);
        G0 = a("measurement.integration.disable_firebase_instance_id", bool, new com.quizlet.shared.usecase.folderstudymaterials.a(10), false);
        H0 = a("measurement.collection.service.update_with_analytics_fix", bool, new com.quizlet.shared.usecase.folderstudymaterials.b(10), false);
        I0 = a("measurement.service.storage_consent_support_version", 203600, new com.quizlet.shared.usecase.folderstudymaterials.c(10), false);
        J0 = a("measurement.service.store_null_safelist", bool2, new com.quizlet.shared.usecase.folderstudymaterials.d(10), false);
        K0 = a("measurement.service.store_safelist", bool2, new com.quizlet.shared.usecase.srs.a(10), false);
        L0 = a("measurement.session_stitching_token_enabled", bool, new retrofit2.adapter.rxjava3.d(10), false);
        M0 = a("measurement.sgtm.upload_queue", bool2, new assistantMode.utils.studiableMetadata.b(11), false);
        N0 = a("measurement.sgtm.google_signal.enable", bool2, new com.google.android.gms.internal.mlkit_common.u(11), false);
        O0 = a("measurement.sgtm.upload_on_uninstall", bool2, new com.google.firebase.heartbeatinfo.e(11), false);
        P0 = a("measurement.sgtm.no_proxy.service", bool, new com.google.firebase.perf.logging.b(11), false);
        Q0 = a("measurement.sgtm.service.batching_on_backgrounded", bool, new com.google.mlkit.common.internal.model.a(11), false);
        R0 = a("measurement.sgtm.no_proxy.client2", bool, new com.google.mlkit.common.sdkinternal.b(11), true);
        S0 = a("measurement.sgtm.client.upload_on_backgrounded.dev", bool, new com.google.mlkit.common.sdkinternal.model.a(11), true);
        T0 = a("measurement.sgtm.client.scion_upload_action", bool2, new com.onetrust.otpublishers.headless.Internal.Helper.h(11), true);
        U0 = a("measurement.gmscore_client_telemetry", bool, new com.quizlet.shared.usecase.folderstudymaterials.b(11), false);
        V0 = a("measurement.rb.attribution.service", bool2, new com.quizlet.shared.usecase.folderstudymaterials.c(11), true);
        W0 = a("measurement.rb.attribution.client2", bool2, new com.quizlet.shared.usecase.folderstudymaterials.d(11), true);
        X0 = a("measurement.rb.attribution.uuid_generation", bool2, new com.quizlet.shared.usecase.srs.a(11), false);
        Y0 = a("measurement.rb.attribution.enable_trigger_redaction", bool2, new com.google.android.material.shape.e(13), false);
        a("measurement.rb.attribution.followup1.service", bool, new com.quizlet.shared.usecase.srs.a(13), false);
        Z0 = a("measurement.rb.attribution.retry_disposition", bool, new com.onetrust.otpublishers.headless.Internal.Helper.h(14), false);
        a1 = a("measurement.client.sessions.enable_fix_background_engagement", bool, new com.google.firebase.heartbeatinfo.e(15), false);
        b1 = a("measurement.fix_engagement_on_reset_analytics_data", bool2, new com.quizlet.shared.usecase.studiableMetadata.a(15), false);
        c1 = a("measurement.set_default_event_parameters_propagate_clear.service.dev", bool, new com.quizlet.shared.usecase.folderstudymaterials.a(16), false);
        d1 = a("measurement.set_default_event_parameters_propagate_clear.client.dev", bool, new com.google.firebase.perf.logging.b(17), false);
        e1 = a("measurement.set_default_event_parameters.fix_deferred_analytics_collection", bool2, new retrofit2.adapter.rxjava3.d(17), false);
        f1 = a("measurement.chimera.parameter.service", bool2, new com.quizlet.shared.usecase.studiableMetadata.a(10), false);
        g1 = a("measurement.service.ad_impression.convert_value_to_double", bool2, new com.quizlet.shared.usecase.folderstudymaterials.a(11), false);
        a("measurement.rb.attribution.service.enable_max_trigger_uris_queried_at_once", bool2, new assistantMode.utils.studiableMetadata.b(12), false);
        a("measurement.remove_conflicting_first_party_apis.dev", bool, new com.google.android.gms.internal.mlkit_common.u(12), false);
        h1 = a("measurement.rb.attribution.service.trigger_uris_high_priority", bool2, new com.google.android.material.shape.e(12), false);
        i1 = a("measurement.backfill_session_ids.service", bool, new com.google.firebase.heartbeatinfo.e(12), false);
        j1 = a("measurement.tcf.consent_fix", bool, new com.google.firebase.perf.logging.b(12), false);
        k1 = a("measurement.experiment.enable_phenotype_experiment_reporting", bool2, new com.google.mlkit.common.internal.model.a(12), false);
        l1 = a("measurement.set_default_event_parameters.fix_service_request_ordering", bool, new com.google.mlkit.common.sdkinternal.b(12), false);
        m1 = a("measurement.set_default_event_parameters.fix_app_update_logging", bool2, new com.onetrust.otpublishers.headless.Internal.Helper.h(12), false);
        n1 = a("measurement.fix_high_memory.prune_ees_config", bool, new com.quizlet.shared.usecase.folderstudymaterials.a(12), false);
        o1 = a("measurement.upload_controller.wait_initialization", bool, new com.quizlet.shared.usecase.folderstudymaterials.b(12), true);
        p1 = a("measurement.admob_plus_removal.client.dev", bool, new com.quizlet.shared.usecase.folderstudymaterials.d(12), false);
        a("measurement.admob_plus_removal.service", bool, new com.quizlet.shared.usecase.srs.a(12), false);
        q1 = a("measurement.service.fix_stop_bundling_bug", bool, new com.quizlet.shared.usecase.studiableMetadata.a(12), false);
        r1 = a("measurement.fix_params_logcat_spam", bool2, new retrofit2.adapter.rxjava3.d(12), false);
    }

    public static C3891s a(String str, Object obj, r rVar, boolean z2) {
        C3891s c3891s = new C3891s(str, obj, rVar);
        if (z2) {
            a.add(c3891s);
        }
        return c3891s;
    }
}
