package com.google.android.gms.ads.internal;

import android.os.Build;
import androidx.camera.camera2.internal.m0;
import androidx.camera.camera2.internal.p0;
import androidx.compose.foundation.gestures.l1;
import com.google.android.gms.ads.internal.util.C1625a;
import com.google.android.gms.ads.internal.util.F;
import com.google.android.gms.ads.internal.util.G;
import com.google.android.gms.ads.internal.util.I;
import com.google.android.gms.ads.internal.util.J;
import com.google.android.gms.cloudmessaging.k;
import com.google.android.gms.internal.ads.C1;
import com.google.android.gms.internal.ads.C1739Nc;
import com.google.android.gms.internal.ads.C1752Pd;
import com.google.android.gms.internal.ads.C2010ed;
import com.google.android.gms.internal.ads.C2084g6;
import com.google.android.gms.internal.ads.C2142hd;
import com.google.android.gms.internal.ads.C2147hi;
import com.google.android.gms.internal.ads.F7;
import com.google.android.gms.internal.ads.L9;
import com.google.android.gms.internal.ads.Os;
import com.google.android.gms.internal.measurement.C3083y1;

/* loaded from: classes2.dex */
public final class j {
    public static final j C = new j();
    public final C1752Pd A;
    public final L9 B;
    public final com.quizlet.shared.usecase.srs.a a;
    public final assistantMode.utils.studiableMetadata.b b;
    public final F c;
    public final L9 d;
    public final C2142hd e;
    public final G f;
    public final C3083y1 g;
    public final C2010ed h;
    public final C1625a i;
    public final C2084g6 j;
    public final com.google.android.gms.common.util.b k;
    public final l1 l;
    public final C1 m;
    public final F7 n;
    public final androidx.camera.camera2.interop.c o;
    public final Os p;
    public final L9 q;
    public final com.quizlet.data.repository.studysetwithcreator.d r;
    public final p0 s;
    public final k t;
    public final com.quizlet.shared.usecase.studiableMetadata.a u;
    public final L9 v;
    public final com.google.firebase.platforminfo.c w;
    public final C2147hi x;
    public final C1739Nc y;
    public final m0 z;

    public j() {
        com.quizlet.shared.usecase.srs.a aVar = new com.quizlet.shared.usecase.srs.a(8);
        assistantMode.utils.studiableMetadata.b bVar = new assistantMode.utils.studiableMetadata.b(9);
        F f = new F();
        L9 l9 = new L9(26);
        C2142hd c2142hd = new C2142hd();
        int i = Build.VERSION.SDK_INT;
        G j = i >= 30 ? new J() : i >= 28 ? new I() : new G();
        C3083y1 c3083y1 = new C3083y1(6);
        C2010ed c2010ed = new C2010ed();
        C1625a c1625a = new C1625a();
        c1625a.a = false;
        c1625a.b = 1.0f;
        C2084g6 c2084g6 = new C2084g6(0);
        com.google.android.gms.common.util.b bVar2 = com.google.android.gms.common.util.b.a;
        l1 l1Var = new l1(4);
        l1Var.b = 0L;
        C1 c1 = new C1(28);
        F7 f7 = new F7();
        androidx.camera.camera2.interop.c cVar = new androidx.camera.camera2.interop.c();
        Os os = new Os(11);
        L9 l92 = new L9(19);
        com.quizlet.data.repository.studysetwithcreator.d dVar = new com.quizlet.data.repository.studysetwithcreator.d(2);
        p0 p0Var = new p0();
        p0Var.a = null;
        p0Var.b = false;
        p0Var.c = null;
        p0Var.e = null;
        p0Var.d = null;
        k kVar = new k(8);
        com.quizlet.shared.usecase.studiableMetadata.a aVar2 = new com.quizlet.shared.usecase.studiableMetadata.a(8);
        L9 l93 = new L9(9);
        com.google.firebase.platforminfo.c cVar2 = new com.google.firebase.platforminfo.c(20);
        C2147hi c2147hi = new C2147hi(19, (byte) 0);
        C1739Nc c1739Nc = new C1739Nc();
        m0 m0Var = new m0(2);
        C1752Pd c1752Pd = new C1752Pd();
        L9 l94 = new L9(21);
        this.a = aVar;
        this.b = bVar;
        this.c = f;
        this.d = l9;
        this.e = c2142hd;
        this.f = j;
        this.g = c3083y1;
        this.h = c2010ed;
        this.i = c1625a;
        this.j = c2084g6;
        this.k = bVar2;
        this.l = l1Var;
        this.m = c1;
        this.n = f7;
        this.o = cVar;
        this.p = os;
        this.q = l92;
        this.r = dVar;
        this.t = kVar;
        this.s = p0Var;
        this.u = aVar2;
        this.v = l93;
        this.w = cVar2;
        this.x = c2147hi;
        this.y = c1739Nc;
        this.z = m0Var;
        this.A = c1752Pd;
        this.B = l94;
    }
}
