package com.google.android.gms.internal.mlkit_vision_barcode;

import com.comscore.streaming.ContentType;
import com.google.android.gms.ads.nonagon.signalgeneration.AbstractC1642h;
import com.onetrust.otpublishers.headless.Public.OTUIDisplayReason.OTUIDisplayReasonCode;
import java.util.HashMap;

/* renamed from: com.google.android.gms.internal.mlkit_vision_barcode.x2, reason: case insensitive filesystem */
/* loaded from: classes2.dex */
public final class C3295x2 implements com.google.firebase.encoders.c {
    public static final com.google.firebase.encoders.b A;
    public static final com.google.firebase.encoders.b A0;
    public static final com.google.firebase.encoders.b B;
    public static final com.google.firebase.encoders.b B0;
    public static final com.google.firebase.encoders.b C;
    public static final com.google.firebase.encoders.b C0;
    public static final com.google.firebase.encoders.b D;
    public static final com.google.firebase.encoders.b D0;
    public static final com.google.firebase.encoders.b E;
    public static final com.google.firebase.encoders.b E0;
    public static final com.google.firebase.encoders.b F;
    public static final com.google.firebase.encoders.b F0;
    public static final com.google.firebase.encoders.b G;
    public static final com.google.firebase.encoders.b G0;
    public static final com.google.firebase.encoders.b H;
    public static final com.google.firebase.encoders.b H0;
    public static final com.google.firebase.encoders.b I;
    public static final com.google.firebase.encoders.b I0;
    public static final com.google.firebase.encoders.b J;
    public static final com.google.firebase.encoders.b J0;
    public static final com.google.firebase.encoders.b K;
    public static final com.google.firebase.encoders.b K0;
    public static final com.google.firebase.encoders.b L;
    public static final com.google.firebase.encoders.b L0;
    public static final com.google.firebase.encoders.b M;
    public static final com.google.firebase.encoders.b M0;
    public static final com.google.firebase.encoders.b N;
    public static final com.google.firebase.encoders.b N0;
    public static final com.google.firebase.encoders.b O;
    public static final com.google.firebase.encoders.b O0;
    public static final com.google.firebase.encoders.b P;
    public static final com.google.firebase.encoders.b P0;
    public static final com.google.firebase.encoders.b Q;
    public static final com.google.firebase.encoders.b Q0;
    public static final com.google.firebase.encoders.b R;
    public static final com.google.firebase.encoders.b R0;
    public static final com.google.firebase.encoders.b S;
    public static final com.google.firebase.encoders.b S0;
    public static final com.google.firebase.encoders.b T;
    public static final com.google.firebase.encoders.b T0;
    public static final com.google.firebase.encoders.b U;
    public static final com.google.firebase.encoders.b U0;
    public static final com.google.firebase.encoders.b V;
    public static final com.google.firebase.encoders.b V0;
    public static final com.google.firebase.encoders.b W;
    public static final com.google.firebase.encoders.b W0;
    public static final com.google.firebase.encoders.b X;
    public static final com.google.firebase.encoders.b X0;
    public static final com.google.firebase.encoders.b Y;
    public static final com.google.firebase.encoders.b Y0;
    public static final com.google.firebase.encoders.b Z;
    public static final com.google.firebase.encoders.b Z0;
    public static final com.google.firebase.encoders.b a0;
    public static final com.google.firebase.encoders.b a1;
    public static final com.google.firebase.encoders.b b0;
    public static final com.google.firebase.encoders.b b1;
    public static final com.google.firebase.encoders.b c0;
    public static final com.google.firebase.encoders.b c1;
    public static final com.google.firebase.encoders.b d0;
    public static final com.google.firebase.encoders.b d1;
    public static final com.google.firebase.encoders.b e0;
    public static final com.google.firebase.encoders.b e1;
    public static final com.google.firebase.encoders.b f0;
    public static final com.google.firebase.encoders.b f1;
    public static final com.google.firebase.encoders.b g0;
    public static final com.google.firebase.encoders.b g1;
    public static final com.google.firebase.encoders.b h0;
    public static final com.google.firebase.encoders.b h1;
    public static final com.google.firebase.encoders.b i0;
    public static final com.google.firebase.encoders.b i1;
    public static final com.google.firebase.encoders.b j0;
    public static final com.google.firebase.encoders.b j1;
    public static final com.google.firebase.encoders.b k0;
    public static final com.google.firebase.encoders.b k1;
    public static final com.google.firebase.encoders.b l0;
    public static final com.google.firebase.encoders.b l1;
    public static final com.google.firebase.encoders.b m0;
    public static final com.google.firebase.encoders.b m1;
    public static final com.google.firebase.encoders.b n0;
    public static final com.google.firebase.encoders.b n1;
    public static final com.google.firebase.encoders.b o0;
    public static final com.google.firebase.encoders.b o1;
    public static final com.google.firebase.encoders.b p0;
    public static final com.google.firebase.encoders.b p1;
    public static final com.google.firebase.encoders.b q;
    public static final com.google.firebase.encoders.b q0;
    public static final com.google.firebase.encoders.b q1;
    public static final com.google.firebase.encoders.b r;
    public static final com.google.firebase.encoders.b r0;
    public static final com.google.firebase.encoders.b r1;
    public static final com.google.firebase.encoders.b s;
    public static final com.google.firebase.encoders.b s0;
    public static final com.google.firebase.encoders.b s1;
    public static final com.google.firebase.encoders.b t;
    public static final com.google.firebase.encoders.b t0;
    public static final com.google.firebase.encoders.b t1;
    public static final com.google.firebase.encoders.b u;
    public static final com.google.firebase.encoders.b u0;
    public static final com.google.firebase.encoders.b u1;
    public static final com.google.firebase.encoders.b v;
    public static final com.google.firebase.encoders.b v0;
    public static final com.google.firebase.encoders.b v1;
    public static final com.google.firebase.encoders.b w;
    public static final com.google.firebase.encoders.b w0;
    public static final com.google.firebase.encoders.b w1;
    public static final com.google.firebase.encoders.b x;
    public static final com.google.firebase.encoders.b x0;
    public static final com.google.firebase.encoders.b x1;
    public static final com.google.firebase.encoders.b y;
    public static final com.google.firebase.encoders.b y0;
    public static final com.google.firebase.encoders.b y1;
    public static final com.google.firebase.encoders.b z;
    public static final com.google.firebase.encoders.b z0;
    public static final C3295x2 a = new C3295x2();
    public static final com.google.firebase.encoders.b b = new com.google.firebase.encoders.b("systemInfo", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(1))));
    public static final com.google.firebase.encoders.b c = new com.google.firebase.encoders.b("eventName", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(2))));
    public static final com.google.firebase.encoders.b d = new com.google.firebase.encoders.b("isThickClient", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(37))));
    public static final com.google.firebase.encoders.b e = new com.google.firebase.encoders.b("clientType", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(61))));
    public static final com.google.firebase.encoders.b f = new com.google.firebase.encoders.b("modelDownloadLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(3))));
    public static final com.google.firebase.encoders.b g = new com.google.firebase.encoders.b("customModelLoadLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(20))));
    public static final com.google.firebase.encoders.b h = new com.google.firebase.encoders.b("customModelInferenceLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(4))));
    public static final com.google.firebase.encoders.b i = new com.google.firebase.encoders.b("customModelCreateLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(29))));
    public static final com.google.firebase.encoders.b j = new com.google.firebase.encoders.b("onDeviceFaceDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(5))));
    public static final com.google.firebase.encoders.b k = new com.google.firebase.encoders.b("onDeviceFaceLoadLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(59))));
    public static final com.google.firebase.encoders.b l = new com.google.firebase.encoders.b("onDeviceTextDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(6))));
    public static final com.google.firebase.encoders.b m = new com.google.firebase.encoders.b("onDeviceTextDetectionLoadLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(79))));
    public static final com.google.firebase.encoders.b n = new com.google.firebase.encoders.b("onDeviceBarcodeDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(7))));
    public static final com.google.firebase.encoders.b o = new com.google.firebase.encoders.b("onDeviceBarcodeLoadLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(58))));
    public static final com.google.firebase.encoders.b p = new com.google.firebase.encoders.b("onDeviceImageLabelCreateLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(48))));

    static {
        H h2 = new H(49);
        HashMap map = new HashMap();
        map.put(L.class, h2);
        q = new com.google.firebase.encoders.b("onDeviceImageLabelLoadLogEvent", assistantMode.refactored.a.o(map));
        r = new com.google.firebase.encoders.b("onDeviceImageLabelDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(18))));
        s = new com.google.firebase.encoders.b("onDeviceObjectCreateLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(26))));
        t = new com.google.firebase.encoders.b("onDeviceObjectLoadLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(27))));
        u = new com.google.firebase.encoders.b("onDeviceObjectInferenceLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(28))));
        v = new com.google.firebase.encoders.b("onDevicePoseDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(44))));
        w = new com.google.firebase.encoders.b("onDeviceSegmentationLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(45))));
        x = new com.google.firebase.encoders.b("onDeviceSmartReplyLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(19))));
        H h3 = new H(21);
        HashMap map2 = new HashMap();
        map2.put(L.class, h3);
        y = new com.google.firebase.encoders.b("onDeviceLanguageIdentificationLogEvent", assistantMode.refactored.a.o(map2));
        z = new com.google.firebase.encoders.b("onDeviceTranslationLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(22))));
        A = new com.google.firebase.encoders.b("cloudFaceDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(8))));
        B = new com.google.firebase.encoders.b("cloudCropHintDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(9))));
        C = new com.google.firebase.encoders.b("cloudDocumentTextDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(10))));
        D = new com.google.firebase.encoders.b("cloudImagePropertiesDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(11))));
        E = new com.google.firebase.encoders.b("cloudImageLabelDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(12))));
        F = new com.google.firebase.encoders.b("cloudLandmarkDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(13))));
        H h4 = new H(14);
        HashMap map3 = new HashMap();
        map3.put(L.class, h4);
        G = new com.google.firebase.encoders.b("cloudLogoDetectionLogEvent", assistantMode.refactored.a.o(map3));
        H = new com.google.firebase.encoders.b("cloudSafeSearchDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(15))));
        I = new com.google.firebase.encoders.b("cloudTextDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(16))));
        J = new com.google.firebase.encoders.b("cloudWebSearchDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(17))));
        K = new com.google.firebase.encoders.b("automlImageLabelingCreateLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(23))));
        L = new com.google.firebase.encoders.b("automlImageLabelingLoadLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(24))));
        M = new com.google.firebase.encoders.b("automlImageLabelingInferenceLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(25))));
        N = new com.google.firebase.encoders.b("isModelDownloadedLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(39))));
        H h5 = new H(40);
        HashMap map4 = new HashMap();
        map4.put(L.class, h5);
        O = new com.google.firebase.encoders.b("deleteModelLogEvent", assistantMode.refactored.a.o(map4));
        P = new com.google.firebase.encoders.b("aggregatedAutomlImageLabelingInferenceLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(30))));
        Q = new com.google.firebase.encoders.b("aggregatedCustomModelInferenceLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(31))));
        R = new com.google.firebase.encoders.b("aggregatedOnDeviceFaceDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(32))));
        S = new com.google.firebase.encoders.b("aggregatedOnDeviceBarcodeDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(33))));
        T = new com.google.firebase.encoders.b("aggregatedOnDeviceImageLabelDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(34))));
        U = new com.google.firebase.encoders.b("aggregatedOnDeviceObjectInferenceLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(35))));
        V = new com.google.firebase.encoders.b("aggregatedOnDeviceTextDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(36))));
        H h6 = new H(46);
        HashMap map5 = new HashMap();
        map5.put(L.class, h6);
        W = new com.google.firebase.encoders.b("aggregatedOnDevicePoseDetectionLogEvent", assistantMode.refactored.a.o(map5));
        X = new com.google.firebase.encoders.b("aggregatedOnDeviceSegmentationLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(47))));
        Y = new com.google.firebase.encoders.b("pipelineAccelerationInferenceEvents", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(69))));
        Z = new com.google.firebase.encoders.b("remoteConfigLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(42))));
        a0 = new com.google.firebase.encoders.b("inputImageConstructionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(50))));
        b0 = new com.google.firebase.encoders.b("leakedHandleEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(51))));
        c0 = new com.google.firebase.encoders.b("cameraSourceLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(52))));
        d0 = new com.google.firebase.encoders.b("imageLabelOptionalModuleLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(53))));
        H h7 = new H(54);
        HashMap map6 = new HashMap();
        map6.put(L.class, h7);
        e0 = new com.google.firebase.encoders.b("languageIdentificationOptionalModuleLogEvent", assistantMode.refactored.a.o(map6));
        f0 = new com.google.firebase.encoders.b("faceDetectionOptionalModuleLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(60))));
        g0 = new com.google.firebase.encoders.b("documentDetectionOptionalModuleLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(85))));
        h0 = new com.google.firebase.encoders.b("documentCroppingOptionalModuleLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(86))));
        i0 = new com.google.firebase.encoders.b("documentEnhancementOptionalModuleLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(87))));
        j0 = new com.google.firebase.encoders.b("nlClassifierOptionalModuleLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(55))));
        k0 = new com.google.firebase.encoders.b("nlClassifierClientLibraryLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(56))));
        l0 = new com.google.firebase.encoders.b("accelerationAllowlistLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(57))));
        H h8 = new H(62);
        HashMap map7 = new HashMap();
        map7.put(L.class, h8);
        m0 = new com.google.firebase.encoders.b("toxicityDetectionCreateEvent", assistantMode.refactored.a.o(map7));
        n0 = new com.google.firebase.encoders.b("toxicityDetectionLoadEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(63))));
        o0 = new com.google.firebase.encoders.b("toxicityDetectionInferenceEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(64))));
        p0 = new com.google.firebase.encoders.b("barcodeDetectionOptionalModuleLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(65))));
        q0 = new com.google.firebase.encoders.b("customImageLabelOptionalModuleLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(66))));
        r0 = new com.google.firebase.encoders.b("codeScannerScanApiEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(67))));
        s0 = new com.google.firebase.encoders.b("codeScannerOptionalModuleEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(68))));
        t0 = new com.google.firebase.encoders.b("onDeviceExplicitContentCreateLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(70))));
        H h9 = new H(71);
        HashMap map8 = new HashMap();
        map8.put(L.class, h9);
        u0 = new com.google.firebase.encoders.b("onDeviceExplicitContentLoadLogEvent", assistantMode.refactored.a.o(map8));
        v0 = new com.google.firebase.encoders.b("onDeviceExplicitContentInferenceLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(72))));
        w0 = new com.google.firebase.encoders.b("aggregatedOnDeviceExplicitContentLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(73))));
        x0 = new com.google.firebase.encoders.b("onDeviceFaceMeshCreateLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(74))));
        y0 = new com.google.firebase.encoders.b("onDeviceFaceMeshLoadLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(75))));
        z0 = new com.google.firebase.encoders.b("onDeviceFaceMeshLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(76))));
        A0 = new com.google.firebase.encoders.b("aggregatedOnDeviceFaceMeshLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(77))));
        B0 = new com.google.firebase.encoders.b("smartReplyOptionalModuleLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(78))));
        H h10 = new H(80);
        HashMap map9 = new HashMap();
        map9.put(L.class, h10);
        C0 = new com.google.firebase.encoders.b("textDetectionOptionalModuleLogEvent", assistantMode.refactored.a.o(map9));
        D0 = new com.google.firebase.encoders.b("onDeviceImageQualityAnalysisCreateLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(81))));
        E0 = new com.google.firebase.encoders.b("onDeviceImageQualityAnalysisLoadLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(82))));
        F0 = new com.google.firebase.encoders.b("onDeviceImageQualityAnalysisLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(83))));
        G0 = new com.google.firebase.encoders.b("aggregatedOnDeviceImageQualityAnalysisLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(84))));
        H0 = new com.google.firebase.encoders.b("imageQualityAnalysisOptionalModuleLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(88))));
        I0 = new com.google.firebase.encoders.b("imageCaptioningOptionalModuleLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(89))));
        J0 = new com.google.firebase.encoders.b("onDeviceImageCaptioningCreateLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(90))));
        H h11 = new H(91);
        HashMap map10 = new HashMap();
        map10.put(L.class, h11);
        K0 = new com.google.firebase.encoders.b("onDeviceImageCaptioningLoadLogEvent", assistantMode.refactored.a.o(map10));
        L0 = new com.google.firebase.encoders.b("onDeviceImageCaptioningInferenceLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(92))));
        M0 = new com.google.firebase.encoders.b("aggregatedOnDeviceImageCaptioningInferenceLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(93))));
        N0 = new com.google.firebase.encoders.b("onDeviceDocumentDetectionCreateLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(94))));
        O0 = new com.google.firebase.encoders.b("onDeviceDocumentDetectionLoadLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(95))));
        P0 = new com.google.firebase.encoders.b("onDeviceDocumentDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(96))));
        Q0 = new com.google.firebase.encoders.b("aggregatedOnDeviceDocumentDetectionLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(97))));
        R0 = new com.google.firebase.encoders.b("onDeviceDocumentCroppingCreateLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(98))));
        H h12 = new H(99);
        HashMap map11 = new HashMap();
        map11.put(L.class, h12);
        S0 = new com.google.firebase.encoders.b("onDeviceDocumentCroppingLoadLogEvent", assistantMode.refactored.a.o(map11));
        T0 = new com.google.firebase.encoders.b("onDeviceDocumentCroppingLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(100))));
        U0 = new com.google.firebase.encoders.b("aggregatedOnDeviceDocumentCroppingLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(101))));
        V0 = new com.google.firebase.encoders.b("onDeviceDocumentEnhancementCreateLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(102))));
        W0 = new com.google.firebase.encoders.b("onDeviceDocumentEnhancementLoadLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(103))));
        X0 = new com.google.firebase.encoders.b("onDeviceDocumentEnhancementLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(104))));
        Y0 = new com.google.firebase.encoders.b("aggregatedOnDeviceDocumentEnhancementLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(OTUIDisplayReasonCode.UIShownCode.BANNER_SHOWN_CONSENT_EXPIRED))));
        Z0 = new com.google.firebase.encoders.b("scannerAutoZoomEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(OTUIDisplayReasonCode.UIShownCode.BANNER_SHOWN_SERVICE_SPECIFIC_OFF))));
        H h13 = new H(OTUIDisplayReasonCode.UIShownCode.BANNER_SHOWN_SYNC_FAILED);
        HashMap map12 = new HashMap();
        map12.put(L.class, h13);
        a1 = new com.google.firebase.encoders.b("lowLightAutoExposureComputationEvent", assistantMode.refactored.a.o(map12));
        b1 = new com.google.firebase.encoders.b("lowLightFrameProcessEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(OTUIDisplayReasonCode.UIShownCode.BANNER_SHOWN_BACKWARD_COMPATIBILITY))));
        c1 = new com.google.firebase.encoders.b("lowLightSceneDetectionEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(OTUIDisplayReasonCode.UIShownCode.BANNER_SHOWN_MOVED_REGION))));
        d1 = new com.google.firebase.encoders.b("onDeviceStainRemovalLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(OTUIDisplayReasonCode.UIShownCode.BANNER_SHOWN_SHOW_BANNER_CALLED))));
        e1 = new com.google.firebase.encoders.b("aggregatedOnDeviceStainRemovalLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(111))));
        f1 = new com.google.firebase.encoders.b("stainRemovalOptionalModuleLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(ContentType.LONG_FORM_ON_DEMAND))));
        g1 = new com.google.firebase.encoders.b("onDeviceShadowRemovalLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(ContentType.LIVE))));
        h1 = new com.google.firebase.encoders.b("aggregatedOnDeviceShadowRemovalLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(114))));
        H h14 = new H(115);
        HashMap map13 = new HashMap();
        map13.put(L.class, h14);
        i1 = new com.google.firebase.encoders.b("shadowRemovalOptionalModuleLogEvent", assistantMode.refactored.a.o(map13));
        j1 = new com.google.firebase.encoders.b("onDeviceDigitalInkSegmentationLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(116))));
        k1 = new com.google.firebase.encoders.b("onDeviceDocumentScannerStartLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(117))));
        l1 = new com.google.firebase.encoders.b("onDeviceDocumentScannerFinishLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(118))));
        m1 = new com.google.firebase.encoders.b("onDeviceDocumentScannerUiStartLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(119))));
        n1 = new com.google.firebase.encoders.b("onDeviceDocumentScannerUiFinishLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(120))));
        o1 = new com.google.firebase.encoders.b("documentScannerUiOptionalModuleSessionStartLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(ContentType.USER_GENERATED_SHORT_FORM_ON_DEMAND))));
        p1 = new com.google.firebase.encoders.b("documentScannerUiOptionalModuleSessionFinishLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(ContentType.USER_GENERATED_LONG_FORM_ON_DEMAND))));
        H h15 = new H(ContentType.USER_GENERATED_LIVE);
        HashMap map14 = new HashMap();
        map14.put(L.class, h15);
        q1 = new com.google.firebase.encoders.b("onDeviceDocumentScannerUiCreateLogEvent", assistantMode.refactored.a.o(map14));
        r1 = new com.google.firebase.encoders.b("onDeviceSubjectSegmentationCreateLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(124))));
        s1 = new com.google.firebase.encoders.b("onDeviceSubjectSegmentationLoadLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(125))));
        t1 = new com.google.firebase.encoders.b("onDeviceSubjectSegmentationInferenceLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(126))));
        u1 = new com.google.firebase.encoders.b("aggregatedOnDeviceSubjectSegmentationLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(127))));
        v1 = new com.google.firebase.encoders.b("subjectSegmentationOptionalModuleLogEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(128))));
        w1 = new com.google.firebase.encoders.b("documentScannerUiModuleScreenViewEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(129))));
        x1 = new com.google.firebase.encoders.b("documentScannerUiModuleScreenClickEvent", assistantMode.refactored.a.o(AbstractC1642h.n(L.class, new H(130))));
        H h16 = new H(131);
        HashMap map15 = new HashMap();
        map15.put(L.class, h16);
        y1 = new com.google.firebase.encoders.b("documentScannerUiModuleScreenErrorEvent", assistantMode.refactored.a.o(map15));
    }

    @Override // com.google.firebase.encoders.a
    public final void a(Object obj, Object obj2) {
        C3306y5 c3306y5 = (C3306y5) obj;
        com.google.firebase.encoders.d dVar = (com.google.firebase.encoders.d) obj2;
        dVar.g(b, c3306y5.a);
        dVar.g(c, c3306y5.b);
        dVar.g(d, null);
        dVar.g(e, c3306y5.c);
        dVar.g(f, null);
        dVar.g(g, null);
        dVar.g(h, null);
        dVar.g(i, null);
        dVar.g(j, null);
        dVar.g(k, null);
        dVar.g(l, null);
        dVar.g(m, null);
        dVar.g(n, c3306y5.d);
        dVar.g(o, c3306y5.e);
        dVar.g(p, null);
        dVar.g(q, null);
        dVar.g(r, null);
        dVar.g(s, null);
        dVar.g(t, null);
        dVar.g(u, null);
        dVar.g(v, null);
        dVar.g(w, null);
        dVar.g(x, null);
        dVar.g(y, null);
        dVar.g(z, null);
        dVar.g(A, null);
        dVar.g(B, null);
        dVar.g(C, null);
        dVar.g(D, null);
        dVar.g(E, null);
        dVar.g(F, null);
        dVar.g(G, null);
        dVar.g(H, null);
        dVar.g(I, null);
        dVar.g(J, null);
        dVar.g(K, null);
        dVar.g(L, null);
        dVar.g(M, null);
        dVar.g(N, null);
        dVar.g(O, null);
        dVar.g(P, null);
        dVar.g(Q, null);
        dVar.g(R, null);
        dVar.g(S, c3306y5.f);
        dVar.g(T, null);
        dVar.g(U, null);
        dVar.g(V, null);
        dVar.g(W, null);
        dVar.g(X, null);
        dVar.g(Y, null);
        dVar.g(Z, null);
        dVar.g(a0, null);
        dVar.g(b0, null);
        dVar.g(c0, null);
        dVar.g(d0, null);
        dVar.g(e0, null);
        dVar.g(f0, null);
        dVar.g(g0, null);
        dVar.g(h0, null);
        dVar.g(i0, null);
        dVar.g(j0, null);
        dVar.g(k0, null);
        dVar.g(l0, null);
        dVar.g(m0, null);
        dVar.g(n0, null);
        dVar.g(o0, null);
        dVar.g(p0, null);
        dVar.g(q0, null);
        dVar.g(r0, null);
        dVar.g(s0, null);
        dVar.g(t0, null);
        dVar.g(u0, null);
        dVar.g(v0, null);
        dVar.g(w0, null);
        dVar.g(x0, null);
        dVar.g(y0, null);
        dVar.g(z0, null);
        dVar.g(A0, null);
        dVar.g(B0, null);
        dVar.g(C0, null);
        dVar.g(D0, null);
        dVar.g(E0, null);
        dVar.g(F0, null);
        dVar.g(G0, null);
        dVar.g(H0, null);
        dVar.g(I0, null);
        dVar.g(J0, null);
        dVar.g(K0, null);
        dVar.g(L0, null);
        dVar.g(M0, null);
        dVar.g(N0, null);
        dVar.g(O0, null);
        dVar.g(P0, null);
        dVar.g(Q0, null);
        dVar.g(R0, null);
        dVar.g(S0, null);
        dVar.g(T0, null);
        dVar.g(U0, null);
        dVar.g(V0, null);
        dVar.g(W0, null);
        dVar.g(X0, null);
        dVar.g(Y0, null);
        dVar.g(Z0, null);
        dVar.g(a1, null);
        dVar.g(b1, null);
        dVar.g(c1, null);
        dVar.g(d1, null);
        dVar.g(e1, null);
        dVar.g(f1, null);
        dVar.g(g1, null);
        dVar.g(h1, null);
        dVar.g(i1, null);
        dVar.g(j1, null);
        dVar.g(k1, null);
        dVar.g(l1, null);
        dVar.g(m1, null);
        dVar.g(n1, null);
        dVar.g(o1, null);
        dVar.g(p1, null);
        dVar.g(q1, null);
        dVar.g(r1, null);
        dVar.g(s1, null);
        dVar.g(t1, null);
        dVar.g(u1, null);
        dVar.g(v1, null);
        dVar.g(w1, null);
        dVar.g(x1, null);
        dVar.g(y1, null);
    }
}
