package assistantMode.refactored.serialization;

import androidx.camera.camera2.internal.p0;
import assistantMode.refactored.modelTypes.Card;
import assistantMode.refactored.modelTypes.CustomMultipleChoiceQuestion;
import assistantMode.refactored.modelTypes.d;
import assistantMode.refactored.types.AndroidWriteMasteryBuckets;
import assistantMode.refactored.types.Checkpoint;
import assistantMode.refactored.types.FillInTheBlankMultipleChoiceQuestion;
import assistantMode.refactored.types.FillInTheBlankQuestion;
import assistantMode.refactored.types.FlashcardsMasteryBuckets;
import assistantMode.refactored.types.IosWriteMasteryBuckets;
import assistantMode.refactored.types.LearnPaywall;
import assistantMode.refactored.types.MixedOptionMatchingQuestion;
import assistantMode.refactored.types.MultipleChoiceQuestion;
import assistantMode.refactored.types.MultipleChoiceSelectAllThatApplyQuestion;
import assistantMode.refactored.types.RevealSelfAssessmentQuestion;
import assistantMode.refactored.types.SeparatedOptionMatchingQuestion;
import assistantMode.refactored.types.SpellMasteryBuckets;
import assistantMode.refactored.types.SpellingQuestion;
import assistantMode.refactored.types.TrueFalseQuestion;
import assistantMode.refactored.types.WebWriteMasteryBuckets;
import assistantMode.refactored.types.WrittenQuestion;
import assistantMode.refactored.types.c;
import assistantMode.refactored.types.g;
import assistantMode.types.BooleanAnswer;
import assistantMode.types.MatchingAnswer;
import assistantMode.types.MatchingGameAnswer;
import assistantMode.types.MultiPartAnswer;
import assistantMode.types.OptionIndexAnswer;
import assistantMode.types.OptionIndicesAnswer;
import assistantMode.types.RevealSelfAssessmentAnswer;
import assistantMode.types.StringAnswer;
import assistantMode.types.gradingContext.ExpectedMatchQuestionPair;
import assistantMode.types.gradingContext.UserMatchQuestionPair;
import assistantMode.types.v;
import com.google.android.gms.internal.mlkit_vision_camera.Z2;
import com.quizlet.remote.model.union.folderwithcreator.b;
import kotlin.jvm.internal.C4950i;
import kotlin.jvm.internal.K;
import kotlinx.serialization.json.q;
import kotlinx.serialization.modules.f;

/* loaded from: classes.dex */
public abstract class a {
    public static final q a;

    static {
        p0 p0Var = new p0();
        b bVar = new b(K.a(d.class));
        bVar.c(K.a(CustomMultipleChoiceQuestion.class), CustomMultipleChoiceQuestion.Companion.serializer());
        bVar.c(K.a(Card.class), Card.Companion.serializer());
        bVar.b(p0Var);
        b bVar2 = new b(K.a(assistantMode.refactored.types.d.class));
        C4950i c4950iA = K.a(SeparatedOptionMatchingQuestion.class);
        SeparatedOptionMatchingQuestion.Companion companion = SeparatedOptionMatchingQuestion.Companion;
        bVar2.c(c4950iA, companion.serializer());
        C4950i c4950iA2 = K.a(MixedOptionMatchingQuestion.class);
        MixedOptionMatchingQuestion.Companion companion2 = MixedOptionMatchingQuestion.Companion;
        bVar2.c(c4950iA2, companion2.serializer());
        C4950i c4950iA3 = K.a(MultipleChoiceQuestion.class);
        MultipleChoiceQuestion.Companion companion3 = MultipleChoiceQuestion.Companion;
        bVar2.c(c4950iA3, companion3.serializer());
        C4950i c4950iA4 = K.a(RevealSelfAssessmentQuestion.class);
        RevealSelfAssessmentQuestion.Companion companion4 = RevealSelfAssessmentQuestion.Companion;
        bVar2.c(c4950iA4, companion4.serializer());
        C4950i c4950iA5 = K.a(TrueFalseQuestion.class);
        TrueFalseQuestion.Companion companion5 = TrueFalseQuestion.Companion;
        bVar2.c(c4950iA5, companion5.serializer());
        C4950i c4950iA6 = K.a(WrittenQuestion.class);
        WrittenQuestion.Companion companion6 = WrittenQuestion.Companion;
        bVar2.c(c4950iA6, companion6.serializer());
        C4950i c4950iA7 = K.a(FillInTheBlankQuestion.class);
        FillInTheBlankQuestion.Companion companion7 = FillInTheBlankQuestion.Companion;
        bVar2.c(c4950iA7, companion7.serializer());
        C4950i c4950iA8 = K.a(FillInTheBlankMultipleChoiceQuestion.class);
        FillInTheBlankMultipleChoiceQuestion.Companion companion8 = FillInTheBlankMultipleChoiceQuestion.Companion;
        bVar2.c(c4950iA8, companion8.serializer());
        C4950i c4950iA9 = K.a(MultipleChoiceSelectAllThatApplyQuestion.class);
        MultipleChoiceSelectAllThatApplyQuestion.Companion companion9 = MultipleChoiceSelectAllThatApplyQuestion.Companion;
        bVar2.c(c4950iA9, companion9.serializer());
        bVar2.b(p0Var);
        b bVar3 = new b(K.a(g.class));
        bVar3.c(K.a(Checkpoint.class), Checkpoint.Companion.serializer());
        bVar3.c(K.a(LearnPaywall.class), LearnPaywall.Companion.serializer());
        bVar3.c(K.a(SeparatedOptionMatchingQuestion.class), companion.serializer());
        bVar3.c(K.a(MixedOptionMatchingQuestion.class), companion2.serializer());
        bVar3.c(K.a(MultipleChoiceQuestion.class), companion3.serializer());
        bVar3.c(K.a(RevealSelfAssessmentQuestion.class), companion4.serializer());
        bVar3.c(K.a(TrueFalseQuestion.class), companion5.serializer());
        bVar3.c(K.a(WrittenQuestion.class), companion6.serializer());
        bVar3.c(K.a(SpellingQuestion.class), SpellingQuestion.Companion.serializer());
        bVar3.c(K.a(FillInTheBlankQuestion.class), companion7.serializer());
        bVar3.c(K.a(FillInTheBlankMultipleChoiceQuestion.class), companion8.serializer());
        bVar3.c(K.a(MultipleChoiceSelectAllThatApplyQuestion.class), companion9.serializer());
        bVar3.b(p0Var);
        b bVar4 = new b(K.a(c.class));
        bVar4.c(K.a(WebWriteMasteryBuckets.class), WebWriteMasteryBuckets.Companion.serializer());
        bVar4.c(K.a(AndroidWriteMasteryBuckets.class), AndroidWriteMasteryBuckets.Companion.serializer());
        bVar4.c(K.a(IosWriteMasteryBuckets.class), IosWriteMasteryBuckets.Companion.serializer());
        bVar4.c(K.a(SpellMasteryBuckets.class), SpellMasteryBuckets.Companion.serializer());
        bVar4.c(K.a(FlashcardsMasteryBuckets.class), FlashcardsMasteryBuckets.Companion.serializer());
        bVar4.b(p0Var);
        b bVar5 = new b(K.a(v.class));
        bVar5.c(K.a(StringAnswer.class), StringAnswer.Companion.serializer());
        bVar5.c(K.a(BooleanAnswer.class), BooleanAnswer.Companion.serializer());
        bVar5.c(K.a(MatchingAnswer.class), MatchingAnswer.Companion.serializer());
        bVar5.c(K.a(MatchingGameAnswer.class), MatchingGameAnswer.Companion.serializer());
        bVar5.c(K.a(OptionIndexAnswer.class), OptionIndexAnswer.Companion.serializer());
        bVar5.c(K.a(OptionIndicesAnswer.class), OptionIndicesAnswer.Companion.serializer());
        bVar5.c(K.a(RevealSelfAssessmentAnswer.class), RevealSelfAssessmentAnswer.Companion.serializer());
        bVar5.c(K.a(MultiPartAnswer.class), MultiPartAnswer.Companion.serializer());
        bVar5.b(p0Var);
        b bVar6 = new b(K.a(assistantMode.types.gradingContext.a.class));
        bVar6.c(K.a(ExpectedMatchQuestionPair.class), ExpectedMatchQuestionPair.Companion.serializer());
        bVar6.c(K.a(UserMatchQuestionPair.class), UserMatchQuestionPair.Companion.serializer());
        bVar6.b(p0Var);
        a = Z2.b(f.a(p0Var.g(), com.quizlet.shared.models.api.a.a));
    }
}
